import {
  CollegeRankEntry,
  CompanyPrepInfo,
  Hackathon,
  ReferralListing,
  MemeItem,
  AnonymousPlacementStory,
  OfferWallPost,
  InterviewQuestion,
  DailyChallengeSet,
  ProjectShowcaseItem,
  OpenSourceRepo,
  StudyGroup,
  NotificationItem,
} from "@/types/community";

export const TOP_COLLEGES: CollegeRankEntry[] = [
  {
    id: "iit-madras",
    name: "IIT Madras",
    state: "Tamil Nadu",
    city: "Chennai",
    type: "IIT",
    logoEmoji: "🏛️",
    shortCode: "IITM",
    badgeColor: "var(--color-danger)",
    overallRank: 1,
    nirfRank: 1,
    avgBerojgarScore: 24,
    placementRate: 97,
    avgPackageLpa: 26.8,
    activeMembers: 1680,
    avgResumeScore: 94,
    interviewSuccessRate: 91,
    codingChallengeScore: 96,
    description: "Ranked #1 in NIRF 2025 Engineering Rankings for 7 consecutive years. Home of Shaastra tech fest, CFI innovation lab, and elite AI/DSA talent.",
    website: "https://www.iitm.ac.in",
    topPerformers: [
      { id: "sm1", name: "Karthik Subramanian", avatarColor: "var(--color-danger)", branch: "CSE", year: "Final", score: 12, xp: 9820, placedCompany: "Jane Street", githubUser: "karthik-m" },
      { id: "sm2", name: "Meera Krishnan", avatarColor: "var(--color-link)", branch: "AI", year: "Final", score: 15, xp: 9150, placedCompany: "Google", githubUser: "meera-ai" },
    ],
    recentOffers: [
      { id: "om1", studentName: "Karthik Subramanian", company: "Jane Street", logo: "📊", role: "Quantitative Engineer", packageLpa: 120, branch: "CSE", date: "1 day ago" },
      { id: "om2", studentName: "Meera Krishnan", company: "Google", logo: "🟢", role: "Software Engineer (L3)", packageLpa: 48, branch: "AI", date: "3 days ago" },
    ],
    upcomingEvents: [
      { id: "em1", title: "CFI Inter-Department DSA Sprint", date: "Aug 12", type: "Hackathon", organizer: "CFI IIT Madras" },
    ],
    githubActivityCount: 15200,
  },
  {
    id: "iit-delhi",
    name: "IIT Delhi",
    state: "Delhi NCR",
    city: "New Delhi",
    type: "IIT",
    logoEmoji: "🏛️",
    shortCode: "IITD",
    badgeColor: "var(--color-danger)",
    overallRank: 2,
    nirfRank: 2,
    avgBerojgarScore: 28,
    placementRate: 95,
    avgPackageLpa: 24.6,
    activeMembers: 1510,
    avgResumeScore: 91,
    interviewSuccessRate: 87,
    codingChallengeScore: 94,
    description: "NIRF 2025 Rank #2. Top startup founders per square meter in India, Tryst tech fest, and high-stakes competitive programming culture.",
    website: "https://www.iitd.ac.in",
    topPerformers: [
      { id: "sd1", name: "Neha Gupta", avatarColor: "var(--color-brand)", branch: "CSE", year: "Final", score: 14, xp: 9410, placedCompany: "Amazon", githubUser: "neha-g" },
      { id: "sd2", name: "Vikas Patel", avatarColor: "var(--color-brand)", branch: "M&C", year: "4th", score: 19, xp: 8800, placedCompany: "Tower Research", githubUser: "vikas-p" },
    ],
    recentOffers: [
      { id: "od1", studentName: "Vikas Patel", company: "Tower Research", logo: "⚡", role: "Quant Trader", packageLpa: 65, branch: "M&C", date: "2 days ago" },
      { id: "od2", studentName: "Neha Gupta", company: "Amazon", logo: "🟧", role: "SDE I", packageLpa: 36, branch: "CSE", date: "4 days ago" },
    ],
    upcomingEvents: [
      { id: "ed1", title: "DevClub HFT Systems Sprint", date: "Aug 18", type: "Workshop", organizer: "DevClub IITD" },
    ],
    githubActivityCount: 13800,
  },
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    state: "Maharashtra",
    city: "Mumbai",
    type: "IIT",
    logoEmoji: "🏛️",
    shortCode: "IITB",
    badgeColor: "var(--color-link)",
    overallRank: 3,
    nirfRank: 3,
    avgBerojgarScore: 30,
    placementRate: 96,
    avgPackageLpa: 25.2,
    activeMembers: 1620,
    avgResumeScore: 93,
    interviewSuccessRate: 89,
    codingChallengeScore: 95,
    description: "NIRF 2025 Rank #3. Powai valley powerhouse. World-class ICPC teams, Mood Indigo energy, and top-tier silicon & AI placement records.",
    website: "https://www.iitb.ac.in",
    topPerformers: [
      { id: "sb1", name: "Aarav Sharma", avatarColor: "var(--color-success)", branch: "CSE", year: "Final", score: 14, xp: 9550, placedCompany: "Google", githubUser: "aarav-codes" },
      { id: "sb2", name: "Riya Sen", avatarColor: "var(--color-link)", branch: "ECE", year: "Final", score: 18, xp: 8950, placedCompany: "Microsoft", githubUser: "riya-dev" },
    ],
    recentOffers: [
      { id: "ob1", studentName: "Aarav Sharma", company: "Google", logo: "🟢", role: "Software Engineer (L3)", packageLpa: 46, branch: "CSE", date: "2 days ago" },
      { id: "ob2", studentName: "Riya Sen", company: "Microsoft", logo: "🟦", role: "Software Engineer II", packageLpa: 43, branch: "ECE", date: "4 days ago" },
    ],
    upcomingEvents: [
      { id: "eb1", title: "Inter-IIT DSA Hackathon", date: "Aug 15", type: "Hackathon", organizer: "IITB Web & Coding Club" },
    ],
    githubActivityCount: 14900,
  },
  {
    id: "iit-kanpur",
    name: "IIT Kanpur",
    state: "Uttar Pradesh",
    city: "Kanpur",
    type: "IIT",
    logoEmoji: "🏛️",
    shortCode: "IITK",
    badgeColor: "var(--color-link)",
    overallRank: 4,
    nirfRank: 4,
    avgBerojgarScore: 32,
    placementRate: 94,
    avgPackageLpa: 22.8,
    activeMembers: 1340,
    avgResumeScore: 90,
    interviewSuccessRate: 86,
    codingChallengeScore: 93,
    description: "NIRF 2025 Rank #4. World-renowned Computer Science department, Techkriti, and legendary algorithmic problem-solving culture.",
    website: "https://www.iitk.ac.in",
    topPerformers: [
      { id: "sk1", name: "Divyansh Mishra", avatarColor: "var(--color-link)", branch: "CSE", year: "Final", score: 16, xp: 9280, placedCompany: "Apple", githubUser: "divyansh-m" },
    ],
    recentOffers: [
      { id: "ok1", studentName: "Divyansh Mishra", company: "Apple", logo: "🍎", role: "Software Engineer", packageLpa: 48, branch: "CSE", date: "1 day ago" },
    ],
    upcomingEvents: [
      { id: "ek1", title: "Cnygma Algorithmic Contest", date: "Aug 19", type: "Hackathon", organizer: "ACA IIT Kanpur" },
    ],
    githubActivityCount: 12100,
  },
  {
    id: "iit-kharagpur",
    name: "IIT Kharagpur",
    state: "West Bengal",
    city: "Kharagpur",
    type: "IIT",
    logoEmoji: "🏛️",
    shortCode: "IITKGP",
    badgeColor: "var(--color-danger)",
    overallRank: 5,
    nirfRank: 5,
    avgBerojgarScore: 33,
    placementRate: 93,
    avgPackageLpa: 22.1,
    activeMembers: 1480,
    avgResumeScore: 89,
    interviewSuccessRate: 84,
    codingChallengeScore: 91,
    description: "NIRF 2025 Rank #5. India's first IIT with 2,100+ acre campus. Kshitij tech fest, massive alumni network, and deep tech research.",
    website: "https://www.iitkgp.ac.in",
    topPerformers: [
      { id: "skg1", name: "Debjyoti Pal", avatarColor: "var(--color-danger)", branch: "CSE", year: "Final", score: 18, xp: 9050, placedCompany: "Uber", githubUser: "debjyoti-p" },
    ],
    recentOffers: [
      { id: "okg1", studentName: "Debjyoti Pal", company: "Uber", logo: "⬛", role: "Backend Engineer", packageLpa: 41, branch: "CSE", date: "3 days ago" },
    ],
    upcomingEvents: [
      { id: "ekg1", title: "Kharagpur Open Source Summit", date: "Aug 25", type: "Tech Fest", organizer: "KGP HackerSociety" },
    ],
    githubActivityCount: 13100,
  },
  {
    id: "nit-trichy",
    name: "NIT Trichy",
    state: "Tamil Nadu",
    city: "Tiruchirappalli",
    type: "NIT",
    logoEmoji: "🏫",
    shortCode: "NITT",
    badgeColor: "var(--color-link)",
    overallRank: 6,
    nirfRank: 9,
    avgBerojgarScore: 36,
    placementRate: 92,
    avgPackageLpa: 20.4,
    activeMembers: 1290,
    avgResumeScore: 87,
    interviewSuccessRate: 82,
    codingChallengeScore: 89,
    description: "NIRF 2025 Rank #9. South India's #1 NIT. Elite Competitive Programming culture, Pragyan tech fest, and top tier product company visits.",
    website: "https://www.nitt.edu",
    topPerformers: [
      { id: "s6", name: "Siddharth Raman", avatarColor: "var(--color-link)", branch: "CSE", year: "Final", score: 21, xp: 8760, placedCompany: "Atlassian" },
    ],
    recentOffers: [
      { id: "o6", studentName: "Siddharth Raman", company: "Atlassian", logo: "🔷", role: "SDE", packageLpa: 52, branch: "CSE", date: "5 days ago" },
    ],
    upcomingEvents: [
      { id: "e4", title: "Open Source CodeFest", date: "Aug 22", type: "Tech Fest", organizer: "Delta Force NITT" },
    ],
    githubActivityCount: 9940,
  },
  {
    id: "bits-pilani",
    name: "BITS Pilani",
    state: "Rajasthan",
    city: "Pilani",
    type: "Private",
    logoEmoji: "🏰",
    shortCode: "BITS",
    badgeColor: "var(--color-brand)",
    overallRank: 7,
    nirfRank: 15,
    avgBerojgarScore: 38,
    placementRate: 91,
    avgPackageLpa: 21.8,
    activeMembers: 1450,
    avgResumeScore: 89,
    interviewSuccessRate: 84,
    codingChallengeScore: 91,
    description: "Top Deemed University. Zero attendance policy, 6-month Practice School (PS-II) corporate internships, and unmatched alumni network.",
    website: "https://www.bits-pilani.ac.in",
    topPerformers: [
      { id: "s7", name: "Ananya Iyer", avatarColor: "var(--color-brand)", branch: "CS", year: "Final", score: 16, xp: 9300, placedCompany: "Microsoft" },
    ],
    recentOffers: [
      { id: "o7", studentName: "Ananya Iyer", company: "Microsoft", logo: "🟦", role: "Software Engineer", packageLpa: 44, branch: "CS", date: "Yesterday" },
    ],
    upcomingEvents: [
      { id: "e5", title: "APOGEE Tech Hack", date: "Sep 01", type: "Hackathon", organizer: "BITS ACM" },
    ],
    githubActivityCount: 12200,
  },
  {
    id: "vit-vellore",
    name: "VIT Vellore",
    state: "Tamil Nadu",
    city: "Vellore",
    type: "Private",
    logoEmoji: "🏢",
    shortCode: "VIT",
    badgeColor: "var(--color-link)",
    overallRank: 8,
    nirfRank: 11,
    avgBerojgarScore: 56,
    placementRate: 87,
    avgPackageLpa: 9.8,
    activeMembers: 3450,
    avgResumeScore: 78,
    interviewSuccessRate: 74,
    codingChallengeScore: 81,
    description: "NIRF 2025 Rank #11 (Private). Massive campus, Super Dream companies (10LPA+), FFCS timetable warfare, and 12,000+ active engineers.",
    website: "https://vit.ac.in",
    topPerformers: [
      { id: "s10", name: "Rohan Kapoor", avatarColor: "var(--color-brand)", branch: "CSE", year: "Final", score: 30, xp: 7800, placedCompany: "PayPal" },
    ],
    recentOffers: [
      { id: "o10", studentName: "Rohan Kapoor", company: "PayPal", logo: "🅿️", role: "SDE 1", packageLpa: 24, branch: "CSE", date: "2 days ago" },
    ],
    upcomingEvents: [
      { id: "e7", title: "Riviera Coding Odyssey", date: "Aug 28", type: "Tech Fest", organizer: "IEEE VIT" },
    ],
    githubActivityCount: 15800,
  },
  {
    id: "brainware-university",
    name: "Brainware University",
    state: "West Bengal",
    city: "Kolkata",
    type: "University",
    logoEmoji: "🎓",
    shortCode: "BWU",
    badgeColor: "var(--color-danger)",
    overallRank: 9,
    nirfRank: 42,
    avgBerojgarScore: 52,
    placementRate: 84,
    avgPackageLpa: 7.2,
    activeMembers: 2150,
    avgResumeScore: 80,
    interviewSuccessRate: 76,
    codingChallengeScore: 83,
    description: "Top regional powerhouse in West Bengal. Heavy daily coding streak community, active industry hackathons, and high tech placement growth!",
    website: "https://www.brainwareuniversity.ac.in",
    topPerformers: [
      { id: "s8", name: "Sourav Ganguly", avatarColor: "var(--color-danger)", branch: "CSE", year: "Final", score: 26, xp: 8100, placedCompany: "TCS Digital" },
      { id: "s9", name: "Priyam Das", avatarColor: "var(--color-success)", branch: "AI", year: "3rd", score: 31, xp: 7600, githubUser: "priyam-ai" },
    ],
    recentOffers: [
      { id: "o8", studentName: "Sourav Ganguly", company: "TCS Digital", logo: "🔴", role: "Digital Innovator", packageLpa: 9.2, branch: "CSE", date: "3 days ago" },
      { id: "o9", studentName: "Megha Banerjee", company: "Wipro", logo: "🟢", role: "Turbo Engineer", packageLpa: 7.0, branch: "IT", date: "1 week ago" },
    ],
    upcomingEvents: [
      { id: "e6", title: "BEC Bengal DSA League", date: "Aug 14", type: "Hackathon", organizer: "BEROJGAR CLUB BWU" },
    ],
    githubActivityCount: 8450,
  },
];

export const COMPANY_HUB_DATA: CompanyPrepInfo[] = [
  {
    id: "amazon",
    slug: "amazon",
    name: "Amazon",
    logo: "🟧",
    logoUrl: "/amazon-logo.png",
    badgeColor: "var(--color-brand)",
    category: "MAANG / Big Tech",
    difficulty: "Hard",
    avgSalaryLpa: { base: 16.5, totalCtc: 34 },
    hiringProcess: [
      { step: 1, title: "Online Assessment (OA)", description: "2 DSA questions (90 min) + Work Simulation (20 min) + Work Style Assessment." },
      { step: 2, title: "Technical Rounds (3-4 Rounds)", description: "50% Leadership Principles (STAR method) + 50% DSA & System Design." },
      { step: 3, title: "Bar Raiser Round", description: "Senior independent interviewer testing candidate against Amazon's global hiring bar." },
    ],
    interviewRounds: [
      { name: "OA Test", focus: "Debugging, 2 DSA questions, Work Simulation", duration: "120 min" },
      { name: "Tech Round 1", focus: "Arrays, Sliders, Amazon Leadership Principles", duration: "60 min" },
      { name: "Tech Round 2", focus: "Graphs & PriorityQueues", duration: "60 min" },
      { name: "Bar Raiser", focus: "System Design & Deep Leadership Drill down", duration: "60 min" },
    ],
    faqs: [
      { question: "How important are Leadership Principles?", answer: "Extremely! 50% of the evaluation depends on your STAR stories for Ownership, Customer Obsession, and Bias for Action." },
      { question: "What DSA topics are asked most at Amazon?", answer: "Binary Trees, PriorityQueue/Heaps, Graph BFS/DFS, and Sliders." },
    ],
    oaQuestions: [
      { title: "Optimize Delivery Logistics Route", topic: "Graph / BFS", difficulty: "Medium", frequency: "High" },
      { title: "Item Fulfillment Center Storage", topic: "PriorityQueue", difficulty: "Medium", frequency: "High" },
    ],
    resumeTips: [
      "Structure bullet points with metrics (e.g. reduced latency by 35%).",
      "Mention AWS or Cloud deployment experience if available.",
    ],
    recentExperiencesCount: 210,
    openPositionsCount: 45,
    requiredSkills: ["Java", "Python", "DSA", "AWS", "Leadership Principles", "System Design"],
    preparationRoadmap: [
      "Prepare 2 STAR stories for all 16 Leadership Principles.",
      "Solve Amazon Top 50 DSA problems on LeetCode.",
    ],
  },
  {
    id: "infosys",
    slug: "infosys",
    name: "Infosys",
    logo: "🔷",
    logoUrl: "/infosys-logo.png",
    badgeColor: "var(--color-link)",
    category: "IT Services / Consulting",
    difficulty: "Medium",
    avgSalaryLpa: { base: 4.0, totalCtc: 9.5 },
    hiringProcess: [
      { step: 1, title: "HackWithInfy / InfyTQ / Off-Campus Test", description: "Online assessment testing Pseudocode, Mathematical Aptitude, and Advanced Coding." },
      { step: 2, title: "Technical Interview", description: "Deep dive into Data Structures, DBMS/SQL, OOP concepts, and Final Year Project." },
      { step: 3, title: "HR & Managerial Interview", description: "Communication assessment, relocation flexibility, and company culture fit." },
    ],
    interviewRounds: [
      { name: "InfyTQ / HackWithInfy Test", focus: "DSA, DBMS, Python/Java Pseudocode", duration: "180 min" },
      { name: "Technical Round", focus: "SQL Queries, DSA, OOPS & Project", duration: "45 min" },
      { name: "HR Interview", focus: "Communication & Cultural Fit", duration: "20 min" },
    ],
    faqs: [
      { question: "What is Specialist Programmer (SP) vs Systems Engineer (SE)?", answer: "Systems Engineer (3.6 LPA), Digital Specialist Engineer (6.2 LPA), Specialist Programmer (9.5 LPA) based on HackWithInfy coding performance." },
    ],
    oaQuestions: [
      { title: "Longest Increasing Subsequence with Step K", topic: "Dynamic Programming", difficulty: "Medium", frequency: "High" },
      { title: "String Frequency Rearrangement", topic: "Strings & Hash", difficulty: "Easy", frequency: "High" },
    ],
    resumeTips: [
      "Highlight certifications in Java, Python, Cloud, or Full-Stack Development.",
      "Add detailed DBMS and SQL project descriptions.",
    ],
    recentExperiencesCount: 310,
    openPositionsCount: 140,
    requiredSkills: ["Java", "Python", "SQL", "DBMS", "OOP", "Aptitude"],
    preparationRoadmap: [
      "Practice HackWithInfy coding questions.",
      "Master SQL Joins, Indexing, and DBMS Normalization.",
    ],
  },
  {
    id: "concentrix",
    slug: "concentrix",
    name: "Concentrix",
    logo: "🌐",
    logoUrl: "/concentrix-logo.png",
    badgeColor: "var(--color-success)",
    category: "Global Tech Giant",
    difficulty: "Medium",
    avgSalaryLpa: { base: 4.5, totalCtc: 8.5 },
    hiringProcess: [
      { step: 1, title: "Aptitude & Technical Screening", description: "Online assessment covering Verbal Ability, Logical Reasoning, and Technical Basics." },
      { step: 2, title: "Technical Interview", description: "Questions on Web Technologies, Cloud Infrastructure, Scripting, and Troubleshooting." },
      { step: 3, title: "Client & HR Round", description: "Evaluation of spoken English fluency, customer-centric problem solving, and adaptability." },
    ],
    interviewRounds: [
      { name: "Online Screening Test", focus: "Logical Reasoning, Verbal, Tech Basics", duration: "90 min" },
      { name: "Tech Interview", focus: "Networking, Linux/Python, Web Dev", duration: "40 min" },
      { name: "HR & Culture Round", focus: "Fluency & Problem Solving", duration: "25 min" },
    ],
    faqs: [
      { question: "What tech roles does Concentrix hire for?", answer: "Concentrix hires Software Engineers, Cloud Support Engineers, Data Analysts, and Automation Specialists." },
    ],
    oaQuestions: [
      { title: "Log File Error Parser", topic: "Regex & Scripting", difficulty: "Easy", frequency: "High" },
      { title: "Customer Session Timeout Filter", topic: "Arrays & Hash", difficulty: "Easy", frequency: "Medium" },
    ],
    resumeTips: [
      "Emphasize strong spoken/written English and customer-focused engineering.",
      "Include experience with Linux, Cloud tools (AWS/Azure), or Automation.",
    ],
    recentExperiencesCount: 165,
    openPositionsCount: 52,
    requiredSkills: ["Python", "JavaScript", "Linux", "Cloud", "Troubleshooting", "Communication"],
    preparationRoadmap: [
      "Review basic Networking and Linux commands.",
      "Practice conversational English and scenario-based technical questions.",
    ],
  },
  {
    id: "ibm",
    slug: "ibm",
    name: "IBM",
    logo: "🔷",
    logoUrl: "/ibm-logo.png",
    badgeColor: "var(--color-link)",
    category: "Global Tech Giant",
    difficulty: "Hard",
    avgSalaryLpa: { base: 7.5, totalCtc: 14.5 },
    hiringProcess: [
      { step: 1, title: "IBM Cognitive Ability Assessment", description: "Interactive gamified games testing spatial reasoning, memory, and numerical agility." },
      { step: 2, title: "Online Coding Test", description: "2 DSA & Algorithmic questions on HackerRank." },
      { step: 3, title: "Technical & Managerial Interview", description: "In-depth questions on Data Structures, Cloud Computing, AI fundamentals, and project architecture." },
    ],
    interviewRounds: [
      { name: "Cognitive Games Test", focus: "Gamified Aptitude & Memory", duration: "45 min" },
      { name: "HackerRank Coding", focus: "Arrays, Strings, Dynamic Programming", duration: "75 min" },
      { name: "Technical Interview", focus: "Architecture, Cloud, AI, DSA", duration: "45 min" },
    ],
    faqs: [
      { question: "What is the IBM Cognitive Assessment like?", answer: "It consists of 5-6 mini games (grid challenge, Resemble, N-back) testing memory and pattern speed." },
    ],
    oaQuestions: [
      { title: "Minimum Operations to Balance Array Weights", topic: "Greedy & Math", difficulty: "Medium", frequency: "High" },
      { title: "IBM Cloud Memory Page Allocation", topic: "Dynamic Programming", difficulty: "Hard", frequency: "Medium" },
    ],
    resumeTips: [
      "Include projects involving AI/ML, Red Hat OpenShift, or Cloud Computing.",
      "Highlight algorithmic problem-solving and software engineering practices.",
    ],
    recentExperiencesCount: 220,
    openPositionsCount: 64,
    requiredSkills: ["Java", "Python", "C++", "Cloud Computing", "AI/ML", "Data Structures"],
    preparationRoadmap: [
      "Practice IBM Cognitive Game tests.",
      "Solve HackerRank Intermediate/Advanced DSA problems.",
    ],
  },
  {
    id: "openai",
    slug: "openai",
    name: "OpenAI",
    logo: "🤖",
    logoUrl: "/openai-logo.png",
    badgeColor: "var(--color-foreground)",
    category: "AI & Frontier Labs",
    difficulty: "Brutal",
    avgSalaryLpa: { base: 45.0, totalCtc: 110.0 },
    hiringProcess: [
      { step: 1, title: "Practical Take-Home / Screen", description: "Build or optimize an AI/LLM system or distributed training pipeline." },
      { step: 2, title: "Technical Coding & Systems (3 Rounds)", description: "Deep systems engineering, PyTorch optimization, distributed memory management, and CUDA/C++." },
      { step: 3, title: "Research & Architecture Deep-Dive", description: "Walkthrough of state-of-the-art AI architectures, transformer optimizations, and safety." },
    ],
    interviewRounds: [
      { name: "Take-Home Project", focus: "LLM Inference / Distributed Systems", duration: "48 hours" },
      { name: "Systems Coding Round 1", focus: "PyTorch, CUDA, High Performance C++", duration: "60 min" },
      { name: "Systems Coding Round 2", focus: "Distributed Training & KV Cache Optimization", duration: "60 min" },
      { name: "Architecture & Culture", focus: "AI Safety, Research Vision, System Design", duration: "60 min" },
    ],
    faqs: [
      { question: "What skills are required for OpenAI Member of Technical Staff?", answer: "Mastery of PyTorch, CUDA, distributed systems (Ray, DeepSpeed), C++, and deep understanding of Transformers." },
    ],
    oaQuestions: [
      { title: "Implement Scaled Dot-Product Attention in CUDA/C++", topic: "GPU Systems & Parallel Code", difficulty: "Hard", frequency: "Very High" },
      { title: "Distributed KV-Cache Eviction Strategy", topic: "Distributed Systems & Memory", difficulty: "Hard", frequency: "High" },
    ],
    resumeTips: [
      "Highlight contributions to PyTorch, vLLM, TensorRT-LLM, or major open-source AI repos.",
      "Show quantitative benchmark improvements (e.g. 4x speedup in throughput).",
    ],
    recentExperiencesCount: 45,
    openPositionsCount: 18,
    requiredSkills: ["Python", "C++", "PyTorch", "CUDA", "Distributed Systems", "Transformers"],
    preparationRoadmap: [
      "Implement Transformers & Attention mechanisms from scratch in Python and CUDA.",
      "Study vLLM, FlashAttention, and Distributed Training (FSDP, Megatron-LM).",
    ],
  },
  {
    id: "google",
    slug: "google",
    name: "Google",
    logo: "🟢",
    badgeColor: "var(--color-link)",
    category: "MAANG / Big Tech",
    difficulty: "Brutal",
    avgSalaryLpa: { base: 18, totalCtc: 42 },
    hiringProcess: [
      { step: 1, title: "Online Assessment (OA)", description: "2 Hard DSA questions in 90 minutes. Strict time complexity requirements (O(N) or O(N log N))." },
      { step: 2, title: "Technical Phone Screen", description: "1-2 DSA problems focused on Graphs, Dynamic Programming, or Trees with live code execution." },
      { step: 3, title: "Onsite Coding Rounds (3 Rounds)", description: "Deep algorithmic problem solving. Emphasis on edge cases, clean code, and time/space tradeoff analysis." },
      { step: 4, title: "Googleyness & Leadership", description: "Behavioral round assessing teamwork, ethics, navigating ambiguity, and growth mindset." },
    ],
    interviewRounds: [
      { name: "OA Test", focus: "Arrays, Strings, Segment Trees, Bit Manipulation", duration: "90 min" },
      { name: "Coding Round 1", focus: "Trees & Graph Traversal (BFS/DFS/Dijkstra)", duration: "45 min" },
      { name: "Coding Round 2", focus: "Dynamic Programming & DP on Trees", duration: "45 min" },
      { name: "Coding Round 3", focus: "System Design / Data Structures Optimization", duration: "45 min" },
      { name: "Googleyness", focus: "Behavioral & Conflict Resolution", duration: "45 min" },
    ],
    faqs: [
      { question: "Is competitive programming mandatory for Google?", answer: "Not mandatory, but solving 300+ LeetCode Medium/Hard problems is required to pass the timed coding rounds." },
      { question: "Can Tier-3 college students get Google referrals?", answer: "Yes! High Berojgar Score, top rank on BEC Leaderboard, and strong GitHub projects frequently get noticed by Google recruiters." },
    ],
    oaQuestions: [
      { title: "Maximum Subarray Sum with K Modifications", topic: "Dynamic Programming", difficulty: "Hard", frequency: "Very High" },
      { title: "Shortest Path in Directed Graph with Colored Edges", topic: "Graph Traversal", difficulty: "Medium", frequency: "High" },
      { title: "Longest Valid Parentheses Substring", topic: "Stack & DP", difficulty: "Hard", frequency: "Medium" },
    ],
    resumeTips: [
      "Quantify your impact using the Google X-Y-Z formula: 'Accomplished [X] as measured by [Y] by doing [Z]'.",
      "List live links to deployed projects with GitHub source code.",
      "Keep resume clean, single-page, ATS-optimized, with no decorative bars or tables.",
    ],
    recentExperiencesCount: 142,
    openPositionsCount: 38,
    requiredSkills: ["C++ / Java / Python", "Data Structures & Algorithms", "System Design", "Problem Solving", "Distributed Systems"],
    preparationRoadmap: [
      "Month 1: Grind Striver A2Z DSA Sheet (Arrays, Binary Search, Trees).",
      "Month 2: Master Graph Algorithms & Dynamic Programming patterns.",
      "Month 3: Practice 50+ Timed LeetCode Hard mock contests.",
      "Month 4: System Design basics & Googleyness behavioral stories preparation.",
    ],
  },
  {
    id: "microsoft",
    slug: "microsoft",
    name: "Microsoft",
    logo: "🟦",
    badgeColor: "var(--color-link)",
    category: "MAANG / Big Tech",
    difficulty: "Hard",
    avgSalaryLpa: { base: 16, totalCtc: 38 },
    hiringProcess: [
      { step: 1, title: "Microsoft Codility OA", description: "3 coding tasks in 110 minutes. Edge case handling is critical." },
      { step: 2, title: "Round 1 (DSA & Code Quality)", description: "Focus on LinkedLists, Binary Trees, and clean OOP principles." },
      { step: 3, title: "Round 2 (DSA & Low-Level Design)", description: "Design a data structure (e.g., LRU Cache, Snake Game) + coding problem." },
      { step: 4, title: "AA Round (As Appropriate)", description: "Senior manager round evaluating cultural fit and architectural thinking." },
    ],
    interviewRounds: [
      { name: "Codility OA", focus: "DSA & Strings", duration: "110 min" },
      { name: "Technical Round 1", focus: "Trees, Tries, Hash Maps", duration: "60 min" },
      { name: "Technical Round 2", focus: "LLD & Object-Oriented Design", duration: "60 min" },
      { name: "AA Manager Round", focus: "Behavioral & System Design", duration: "60 min" },
    ],
    faqs: [
      { question: "What is the Codility scoring criteria?", answer: "Codility tests correctness AND efficiency. Hidden test cases contain large input constraints." },
    ],
    oaQuestions: [
      { title: "Find Min Deletions to Make Frequency of Letters Unique", topic: "Greedy & Hash", difficulty: "Medium", frequency: "High" },
      { title: "Serialize and Deserialize Binary Tree", topic: "Trees", difficulty: "Hard", frequency: "High" },
    ],
    resumeTips: [
      "Highlight C#/.NET, C++, or Java backend projects.",
      "Include achievements in hackathons or open-source PRs.",
    ],
    recentExperiencesCount: 98,
    openPositionsCount: 25,
    requiredSkills: ["C++", "C#", "Java", "DSA", "System Design", "OOP"],
    preparationRoadmap: [
      "Step 1: Solve top 100 Microsoft tagged questions on LeetCode.",
      "Step 2: Practice Low-Level Design (LLD) patterns (Factory, Observer, Singleton).",
    ],
  },
];

export const HACKATHONS_DATA: Hackathon[] = [
  {
    id: "h1",
    title: "Smart India Hackathon 2026",
    organizer: "Ministry of Education, Govt of India",
    logoEmoji: "🇮🇳",
    mode: "Offline",
    location: "Multiple Nodal Centers, India",
    tags: ["AI", "Open Source", "Web", "Flutter"],
    prizeMoney: "₹1,00,000 per Problem Statement",
    registrationDeadline: "2026-08-30",
    startDate: "2026-09-15",
    difficulty: "Intermediate",
    registeredCount: 8420,
    overview: "Nationwide initiative to provide students a platform to solve real-world pressing problems of ministries and industries.",
    timeline: [
      { date: "Aug 30", title: "Internal College Nomination Deadline" },
      { date: "Sep 05", title: "Shortlisting Announcement" },
      { date: "Sep 15-16", title: "36-Hour Non-stop Grand Finale" },
    ],
    prizes: [
      { rank: "Winner", amount: "₹1,00,000" },
      { rank: "1st Runner Up", amount: "₹75,000" },
    ],
    resources: [
      { name: "SIH Problem Statements PDF", url: "#" },
      { name: "Pitch Deck Template", url: "#" },
    ],
    previousWinners: [
      { teamName: "ByteBusters", project: "AI Farmer Assistance Bot", year: "2025" },
    ],
    teamRequests: [
      { id: "tr1", authorName: "Priya Das", college: "Brainware University", rolesNeeded: ["Backend (Node.js)", "AI Engineer"], pitch: "Building an automated grievance portal for civic issues using Gemini API.", contact: "priya@gmail.com" },
      { id: "tr2", authorName: "Rahul V", college: "VIT Vellore", rolesNeeded: ["Flutter Developer"], pitch: "Working on Smart Healthcare App with offline sync.", contact: "rahul@vit.ac.in" },
    ],
    discussions: [
      { author: "Ankit K", text: "Anyone interested in Problem Statement SIH1402 (Traffic AI)?", timeAgo: "2 hours ago" },
    ],
  },
  {
    id: "h2",
    title: "ETHIndia 2026",
    organizer: "Devfolio & Polygon",
    logoEmoji: "🔷",
    mode: "Offline",
    location: "Bengaluru, Karnataka",
    tags: ["Blockchain", "Web3", "Open Source"],
    prizeMoney: "$100,000 Pool",
    registrationDeadline: "2026-09-10",
    startDate: "2026-10-01",
    difficulty: "Advanced",
    registeredCount: 4200,
    overview: "Asia's largest Ethereum hackathon bringing together top Web3 builders, founders, and engineers.",
    timeline: [
      { date: "Sep 10", title: "RSVP Deadline" },
      { date: "Oct 01", title: "Hacking Begins" },
    ],
    prizes: [
      { rank: "Grand Prize", amount: "$20,000" },
      { rank: "Track Bounties", amount: "$80,000" },
    ],
    resources: [
      { name: "Solidity Starter Kit", url: "#" },
    ],
    previousWinners: [
      { teamName: "ZeroKnowledge", project: "Private Payroll on Chain", year: "2025" },
    ],
    teamRequests: [
      { id: "tr3", authorName: "Arjun Nair", college: "IIT Madras", rolesNeeded: ["Solidity Dev", "UI Designer"], pitch: "Building decentralized Micro-Insurance on Arbitrum.", contact: "arjun@web3.io" },
    ],
    discussions: [
      { author: "DevX", text: "Looking for a mentor for Account Abstraction ERC-4337.", timeAgo: "4 hours ago" },
    ],
  },
  {
    id: "h3",
    title: "Google Girl Hackathon 2026",
    organizer: "Google India",
    logoEmoji: "🟢",
    mode: "Online",
    location: "Virtual",
    tags: ["AI", "Web", "Open Source"],
    prizeMoney: "Pre-Placement Interviews (PPI) + SWAGs",
    registrationDeadline: "2026-08-25",
    startDate: "2026-09-01",
    difficulty: "Intermediate",
    registeredCount: 12500,
    overview: "A program for women in engineering across India providing learning, mentorship, and career paths at Google.",
    timeline: [
      { date: "Aug 25", title: "Registration Closes" },
      { date: "Sep 01", title: "Learning Cohort Begins" },
    ],
    prizes: [
      { rank: "Top Performers", amount: "Google PPIs + Pixel Devices" },
    ],
    resources: [
      { name: "Google Study Jam Guide", url: "#" },
    ],
    previousWinners: [
      { teamName: "TechWomen", project: "AI Braille Reader", year: "2025" },
    ],
    teamRequests: [],
    discussions: [],
  },
];

export const REFERRALS_DATA: ReferralListing[] = [
  {
    id: "ref1",
    referrerName: "Saurabh Mishra",
    company: "Google",
    role: "Software Engineer II",
    experienceYears: 4,
    avatarColor: "var(--color-success)",
    availableLimitMonthly: 5,
    usedThisMonth: 2,
    preferredSkills: ["LeetCode 300+", "React / Next.js", "C++ / Java", "Good GitHub"],
    notes: "I review resumes on weekends. Please ensure your resume is ATS clean and has live links before requesting.",
  },
  {
    id: "ref2",
    referrerName: "Ananya Deshmukh",
    company: "Microsoft",
    role: "SDE 2",
    experienceYears: 3,
    avatarColor: "var(--color-link)",
    availableLimitMonthly: 4,
    usedThisMonth: 1,
    preferredSkills: ["Data Structures", "System Design Basics", "C# / C++ / Java"],
    notes: "Happy to refer students with strong problem solving credentials and Berojgar Score under 40!",
  },
  {
    id: "ref3",
    referrerName: "Karthik Raja",
    company: "Amazon",
    role: "SDE 1",
    experienceYears: 2,
    avatarColor: "var(--color-brand)",
    availableLimitMonthly: 6,
    usedThisMonth: 4,
    preferredSkills: ["Java", "AWS", "System Design", "Projects"],
    notes: "Please write a concise 2-sentence intro showing how your skills match Amazon's Leadership Principles.",
  },
  {
    id: "ref4",
    referrerName: "Tanvi Saxena",
    company: "Atlassian",
    role: "Frontend Engineer",
    experienceYears: 3,
    avatarColor: "var(--color-brand)",
    availableLimitMonthly: 3,
    usedThisMonth: 1,
    preferredSkills: ["React", "TypeScript", "UI/UX", "TailwindCSS"],
    notes: "Looking for students who build real web apps with clean code on GitHub.",
  },
];

export const MEMES_DATA: MemeItem[] = [
  {
    id: "m1",
    author: "Rohan_404",
    college: "Brainware University",
    avatarColor: "var(--color-danger)",
    caption: "Me explaining to HR why 6 months gap was actually 'Self-driven Deep Learning Exploration' (I was playing Valorant) 🤡",
    category: "Placement",
    likes: 420,
    commentsCount: 68,
    shares: 112,
    timeAgo: "2 hours ago",
    comments: [
      { id: "c1", author: "Aman", text: "Bro calling Valorant 'real-time spatial decision making' in resume 😭", timeAgo: "1 hour ago" },
      { id: "c2", author: "Sneha", text: "Standard Tier-3 experience haha", timeAgo: "30 min ago" },
    ],
  },
  {
    id: "m2",
    author: "NullPointer_Abhi",
    college: "VIT Vellore",
    avatarColor: "var(--color-link)",
    caption: "Code works on local localhost:3000. Code on recruiter's live demo: 'Cannot read properties of undefined' 💀",
    category: "Coding",
    likes: 680,
    commentsCount: 94,
    shares: 205,
    timeAgo: "5 hours ago",
    comments: [
      { id: "c3", author: "DevPro", text: "Always test production build before demo call! lesson learned hard way.", timeAgo: "3 hours ago" },
    ],
  },
  {
    id: "m3",
    author: "Anonymous Engineer",
    college: "NIT Trichy",
    avatarColor: "var(--color-muted)",
    caption: "Confession: I spent 4 years studying Computer Science just to figure out that my real passion was sleep.",
    category: "Confession",
    likes: 910,
    commentsCount: 130,
    shares: 340,
    timeAgo: "1 day ago",
    isConfession: true,
  },
  {
    id: "m4",
    author: "DSA_Survivor",
    college: "IIT Delhi",
    avatarColor: "var(--color-success)",
    caption: "Day 87 of telling myself 'just 1 more LeetCode Medium before sleeping' at 3:30 AM 🔋",
    category: "Interview",
    likes: 540,
    commentsCount: 42,
    shares: 88,
    timeAgo: "1 day ago",
  },
];

export const PLACEMENT_STORIES_DATA: AnonymousPlacementStory[] = [
  {
    id: "ps1",
    category: "Ghosted by HR",
    title: "Passed 4 rounds at a dream unicorn, then complete radio silence for 3 weeks",
    content: "Cleared OA, 2 Tech Rounds, and Managerial Round. Recruiter said 'expect offer letter by Monday'. Monday came and went. Emailed thrice. Turned out the team's head-count got frozen. Morale crushed, but back to grinding on BEC!",
    company: "Swiggy",
    branch: "CSE",
    role: "SDE-1",
    college: "Tier-2 College",
    difficulty: "Hard",
    upvotes: 340,
    reactions: { cry: 180, skull: 95, rocket: 12, clown: 64, clap: 40 },
    commentsCount: 52,
    timeAgo: "3 days ago",
  },
  {
    id: "ps2",
    category: "Placement Experience",
    title: "How I cleared TCS Digital despite 6.8 CGPA",
    content: "Everyone told me CGPA would kill my chances. Focused 100% on Advanced Coding in TCS NQT. Solved 150 Array & String problems. In interview, explained my fullstack project with full confidence. CGPA doesn't define your skills!",
    company: "TCS Digital",
    branch: "IT",
    role: "Digital Developer (7 LPA)",
    college: "Brainware University",
    difficulty: "Medium",
    upvotes: 620,
    reactions: { cry: 5, skull: 2, rocket: 410, clown: 4, clap: 280 },
    commentsCount: 84,
    timeAgo: "5 days ago",
  },
  {
    id: "ps3",
    category: "Funny Story",
    title: "Accidentally shared my meme folder during screen share in technical interview",
    content: "Interviewer asked to show my GitHub code. I accidentally shared screen on Chrome tab 4 which had 'HR ghosting memes'. Interviewer burst out laughing, asked me to explain the joke, and then asked 2 binary tree questions. Got selected! 😂",
    company: "Cognizant",
    branch: "ECE",
    role: "GenC Developer",
    college: "SRM Chennai",
    difficulty: "Easy",
    upvotes: 890,
    reactions: { cry: 12, skull: 140, rocket: 210, clown: 320, clap: 350 },
    commentsCount: 110,
    timeAgo: "1 week ago",
  },
];

export const OFFER_WALL_DATA: OfferWallPost[] = [
  {
    id: "ow1",
    studentName: "Priyam Das",
    avatarColor: "var(--color-success)",
    college: "Brainware University",
    branch: "Computer Science & AI",
    company: "TCS Digital",
    logo: "🔴",
    role: "Digital Innovator",
    packageLpa: 9.0,
    offerDate: "2026-07-20",
    prepTimeMonths: 5,
    journey: "Started with a brutal 82 Berojgar score on BEC 5 months ago. Rebuilt my resume, solved daily DSA challenges, and completed 3 fullstack projects.",
    resourcesUsed: ["BEC Daily DSA Challenge", "Striver A2Z Sheet", "NeetCode 150"],
    resumeHighlights: ["AI Career Coach Web App", "GitHub 100-day commit streak"],
    congratulationsCount: 184,
    questionsCount: 29,
  },
  {
    id: "ow2",
    studentName: "Aarav Sharma",
    avatarColor: "var(--color-link)",
    college: "IIT Bombay",
    branch: "CSE",
    company: "Google",
    logo: "🟢",
    role: "Software Engineer (L3)",
    packageLpa: 45.0,
    offerDate: "2026-07-18",
    prepTimeMonths: 12,
    journey: "Focused heavily on Graph theory, Segment trees, and mock interviews. Constant consistency and staying accountable on the BEC Leaderboard kept me motivated.",
    resourcesUsed: ["LeetCode Hard Contests", "BEC Mock Interview Simulator"],
    resumeHighlights: ["Distributed Cache in Rust", "GSoC 2025 Contributor"],
    congratulationsCount: 420,
    questionsCount: 64,
  },
];

export const DAILY_CHALLENGE_DATA: DailyChallengeSet = {
  date: "2026-07-23",
  dsa: {
    title: "Container With Most Water",
    difficulty: "Medium",
    description: "Given n non-negative integers height[i] where each represents a point at coordinate (i, height[i]). Find two lines that together with the x-axis form a container containing the most water.",
    codeTemplate: `function maxArea(height) {\n  // Write your O(N) Two-Pointer solution here\n  let maxWater = 0;\n  let left = 0;\n  let right = height.length - 1;\n  \n  while (left < right) {\n    let minH = Math.min(height[left], height[right]);\n    maxWater = Math.max(maxWater, minH * (right - left));\n    if (height[left] < height[right]) left++;\n    else right--;\n  }\n  return maxWater;\n}`,
    testCases: [
      { input: "[1,8,6,2,5,4,8,3,7]", output: "49" },
      { input: "[1,1]", output: "1" },
    ],
    solutionExplanation: "Use Two Pointers starting at extremities (left = 0, right = n-1). Move the pointer pointing to the smaller height inwards to maximize potential area.",
  },
  aptitude: {
    question: "A train running at 72 km/hr passes a telegraph post in 15 seconds. What is the length of the train?",
    options: ["250 meters", "300 meters", "350 meters", "400 meters"],
    correctIndex: 1,
    explanation: "Speed in m/s = 72 * (5/18) = 20 m/s. Distance = Speed * Time = 20 * 15 = 300 meters.",
  },
  sql: {
    question: "Which SQL clause is used to filter records AFTER grouping has taken place?",
    schema: "SELECT department_id, AVG(salary) FROM employees GROUP BY department_id ...",
    options: ["WHERE", "HAVING", "ORDER BY", "FILTER"],
    correctIndex: 1,
    explanation: "HAVING is used to filter aggregated data after GROUP BY. WHERE filters rows before aggregation.",
  },
  csMcq: {
    question: "In Operating Systems, which CPU scheduling algorithm can lead to starvation for long processes?",
    subject: "OS",
    options: ["Round Robin (RR)", "First-Come First-Served (FCFS)", "Shortest Job First (SJF)", "Priority Scheduling"],
    correctIndex: 2,
    explanation: "SJF (or Shortest Remaining Time First) can cause starvation if short processes keep arriving continuously.",
  },
  aiMcq: {
    question: "What is the primary function of the Attention mechanism in Transformer architecture (e.g. LLMs)?",
    options: [
      "To reduce matrix dimensions to zero",
      "To calculate dynamic context weights between token tokens in a sequence",
      "To compress images into JPEG format",
      "To replace backpropagation completely"
    ],
    correctIndex: 1,
    explanation: "Self-Attention computes query-key similarity matrices to assign dynamic context weights across tokens in parallel.",
  },
};

export const PROJECTS_DATA: ProjectShowcaseItem[] = [
  {
    id: "p1",
    authorName: "Priyam Das",
    authorCollege: "Brainware University",
    avatarColor: "var(--color-success)",
    title: "AI Resume & ATS Optimizer",
    tagline: "Instant feedback and live AST keyword analysis for engineering students",
    description: "Built with Next.js 16, TailwindCSS, and Gemini API. Parses PDF resumes, scores ATS readability, and suggests exact bullet point improvements.",
    imageUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&auto=format&fit=crop&q=80",
    githubUrl: "https://github.com/priyam/ats-optimizer",
    demoUrl: "https://berojgarengineer.club/resume",
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "Gemini AI"],
    likes: 245,
    forks: 38,
    commentsCount: 19,
    timeAgo: "2 days ago",
  },
  {
    id: "p2",
    authorName: "Siddharth Raman",
    authorCollege: "NIT Trichy",
    avatarColor: "var(--color-link)",
    title: "DevPulse - Real-time Collaborative Code IDE",
    tagline: "Browser-based code editor with WebSockets & WebAssembly compiler",
    description: "Supports C++, Python, and JS execution in browser sandbox with operational transformation for live pair programming.",
    imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80",
    githubUrl: "https://github.com/siddharth/devpulse",
    demoUrl: "https://devpulse-demo.vercel.app",
    techStack: ["React", "WebSockets", "WebAssembly", "Node.js"],
    likes: 380,
    forks: 72,
    commentsCount: 31,
    timeAgo: "4 days ago",
  },
];

export const OPEN_SOURCE_REPOS: OpenSourceRepo[] = [
  {
    id: "os1",
    name: "free-programming-books-india",
    owner: "berojgar-community",
    language: "JavaScript",
    description: "Curated collection of free engineering textbooks, DSA guides, and interview cheatsheets.",
    stars: 1420,
    goodFirstIssues: 12,
    badgeReward: "Open Source Contributor",
    repoUrl: "https://github.com/berojgar-club/free-books",
  },
  {
    id: "os2",
    name: "ai-placement-agent-python",
    owner: "berojgar-community",
    language: "Python",
    description: "Open-source Python CLI for automated mock interview feedback using Gemini 1.5 Flash.",
    stars: 890,
    goodFirstIssues: 8,
    badgeReward: "GitHub Hero",
    repoUrl: "https://github.com/berojgar-club/ai-placement-cli",
  },
  {
    id: "os3",
    name: "flutter-engineering-ui-kit",
    owner: "berojgar-community",
    language: "Flutter",
    description: "Cross-platform mobile UI widgets for student portfolios and campus apps.",
    stars: 650,
    goodFirstIssues: 15,
    badgeReward: "Flutter Champion",
    repoUrl: "https://github.com/berojgar-club/flutter-ui-kit",
  },
];

export const STUDY_GROUPS_DATA: StudyGroup[] = [
  {
    id: "g1",
    name: "DSA Grind 75 & Striver A2Z",
    category: "DSA Preparation",
    emoji: "⚡",
    description: "Daily 1-hour problem solving sprint together. Voice room active every evening 9 PM - 10 PM!",
    membersCount: 1420,
    activeVoiceUsers: 14,
    discussions: [
      { author: "Kunal", text: "Today's problem: Container With Most Water! Join voice room 1.", timeAgo: "10 min ago" },
    ],
    resources: [
      { title: "Striver A2Z Sheet PDF", link: "#", type: "PDF" },
      { title: "NeetCode 150 Checklist", link: "#", type: "Link" },
    ],
    upcomingEvents: [
      { title: "Graph DP Mock Contest", time: "Today 9:00 PM" },
    ],
  },
  {
    id: "g2",
    name: "GATE CSE 2027 Aspirants",
    category: "GATE CSE",
    emoji: "📚",
    description: "Dedicated focus group for GATE Computer Science. Standard books, PYQs, and test series analysis.",
    membersCount: 980,
    activeVoiceUsers: 6,
    discussions: [
      { author: "Rohan", text: "Discussing DBMS Normalization (3NF vs BCNF) in Voice Room 2.", timeAgo: "25 min ago" },
    ],
    resources: [
      { title: "GATE CS Last 15 Year PYQ Book", link: "#", type: "Drive" },
    ],
    upcomingEvents: [
      { title: "OS Paging vs Segmentation Quiz", time: "Tomorrow 6:00 PM" },
    ],
  },
  {
    id: "g3",
    name: "Google & MAANG Interview Squad",
    category: "Google Interview",
    emoji: "🟢",
    description: "Peer mock interviews, System Design discussions, and Googleyness behavioral practice.",
    membersCount: 1150,
    activeVoiceUsers: 9,
    discussions: [
      { author: "Aarav", text: "Who wants a peer mock interview for System Design (URL Shortener)?", timeAgo: "1 hour ago" },
    ],
    resources: [
      { title: "Grokking System Design Notes", link: "#", type: "Doc" },
    ],
    upcomingEvents: [
      { title: "Live Peer Mock Session", time: "Saturday 4:00 PM" },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n1",
    title: "Leaderboard Alert 🏆",
    message: "Aarav Sharma passed you on the Weekly Leaderboard! Take today's challenge to reclaim your rank.",
    type: "rank",
    timeAgo: "10 min ago",
    read: false,
    link: "/leaderboard",
  },
  {
    id: "n2",
    title: "New Referral Available 🤝",
    message: "Saurabh Mishra from Google opened 5 new referral slots for SDE positions.",
    type: "referral",
    timeAgo: "1 hour ago",
    read: false,
    link: "/referrals",
  },
  {
    id: "n3",
    title: "Hackathon Alert 🚀",
    message: "Smart India Hackathon 2026 registration deadline is in 7 days! Find teammates now.",
    type: "hackathon",
    timeAgo: "3 hours ago",
    read: false,
    link: "/hackathons",
  },
];
