import { LeaderboardEntry, SocialProofEntry, DailyChallenge, CommunityPost } from "@/types";

export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  {
    rank: 1,
    name: "Aryan Kumar",
    college: "IIT Kharagpur",
    branch: "CSE",
    state: "West Bengal",
    year: "4",
    score: 94,
    projects: 12,
    xp: 18400,
    offer: "Google",
    badgeIds: ["placement-slayer", "github-beast", "dsa-hero", "top-1-percent", "overachiever"],
    avatarColor: "#6366f1",
  },
  {
    rank: 2,
    name: "Rahul Singh",
    college: "NIT Durgapur",
    branch: "ECE",
    state: "West Bengal",
    year: "4",
    score: 89,
    projects: 16,
    xp: 15800,
    offer: "Amazon",
    badgeIds: ["placement-slayer", "github-beast", "resume-warrior", "streak-7"],
    avatarColor: "#f59e0b",
  },
  {
    rank: 3,
    name: "Anik Banerjee",
    college: "Brainware University",
    branch: "CSE",
    state: "West Bengal",
    year: "4",
    score: 87,
    projects: 18,
    xp: 14900,
    offer: "Microsoft",
    badgeIds: ["placement-slayer", "dsa-hero", "night-coder", "interview-master"],
    avatarColor: "#10b981",
  },
  {
    rank: 4,
    name: "Priya Sharma",
    college: "VIT Vellore",
    branch: "IT",
    state: "Tamil Nadu",
    year: "4",
    score: 84,
    projects: 9,
    xp: 13200,
    offer: "Flipkart",
    badgeIds: ["placement-slayer", "resume-warrior", "github-beast"],
    avatarColor: "#ec4899",
  },
  {
    rank: 5,
    name: "Rohit Patel",
    college: "NIT Surat",
    branch: "CSE",
    state: "Gujarat",
    year: "4",
    score: 81,
    projects: 7,
    xp: 12100,
    offer: "Infosys",
    badgeIds: ["placement-slayer", "streak-7", "first-blood"],
    avatarColor: "#3b82f6",
  },
  {
    rank: 6,
    name: "Sneha Gupta",
    college: "Jadavpur University",
    branch: "CSE",
    state: "West Bengal",
    year: "3",
    score: 78,
    projects: 6,
    xp: 11400,
    offer: "TCS",
    badgeIds: ["dsa-hero", "resume-warrior", "first-blood"],
    avatarColor: "#8b5cf6",
  },
  {
    rank: 7,
    name: "Ananya Roy",
    college: "BITS Pilani",
    branch: "CS",
    state: "Rajasthan",
    year: "4",
    score: 75,
    projects: 11,
    xp: 10800,
    offer: "Accenture",
    badgeIds: ["github-beast", "night-coder", "resume-warrior"],
    avatarColor: "#f97316",
  },
  {
    rank: 8,
    name: "Vikram Das",
    college: "KIIT Bhubaneswar",
    branch: "CSE",
    state: "Odisha",
    year: "4",
    score: 72,
    projects: 5,
    xp: 9900,
    offer: "Wipro",
    badgeIds: ["first-blood", "resume-warrior"],
    avatarColor: "#14b8a6",
  },
  {
    rank: 9,
    name: "Meera Nair",
    college: "CET Kerala",
    branch: "CSE",
    state: "Kerala",
    year: "4",
    score: 68,
    projects: 4,
    xp: 8700,
    offer: "Startup",
    badgeIds: ["first-blood", "night-coder"],
    avatarColor: "#ef4444",
  },
  {
    rank: 10,
    name: "Dev Mishra",
    college: "LNCT Bhopal",
    branch: "IT",
    state: "Madhya Pradesh",
    year: "3",
    score: 64,
    projects: 3,
    xp: 7600,
    offer: "IBM",
    badgeIds: ["first-blood"],
    avatarColor: "#6b7280",
  },
];

export const SOCIAL_PROOF_DATA: SocialProofEntry[] = [
  { name: "Rohit Patel", college: "LNCT Bhopal", branch: "CSE", beforeScore: 84, afterScore: 32, company: "TCS Digital", role: "SDE" },
  { name: "Sourav Ray", college: "Brainware Univ", branch: "CSE", beforeScore: 91, afterScore: 20, company: "Accenture", role: "Analyst" },
  { name: "Ananya Roy", college: "BITS Pilani", branch: "CS", beforeScore: 76, afterScore: 15, company: "Y Combinator Startup", role: "Backend Dev" },
  { name: "Kiran Sharma", college: "VIT Vellore", branch: "IT", beforeScore: 88, afterScore: 24, company: "Infosys", role: "SDE-1" },
  { name: "Divya Nair", college: "CET Kerala", branch: "ECE", beforeScore: 79, afterScore: 18, company: "Wipro Turbo", role: "Developer" },
];

export const MARQUEE_STATS = [
  "12,420+ Student Engineers Tested",
  "88% Identified Resume & ATS Skill Gaps",
  "847 Daily Challenges Completed Today",
  "Average Risk Score Reduction: -35 pts",
  "4.9/5 Student Rating for Brutal Honesty",
  "350+ Campus Referrals Requested This Month",
  "5,000+ LeetCode DSA Solutions Submitted",
];

export const DAILY_CHALLENGE_POOL: DailyChallenge[] = [
  {
    id: "dsa-1",
    title: "Solve 2 Medium DSA Problems",
    description: "LeetCode, GFG, or HackerRank. Arrays or Strings preferred.",
    xpReward: 50,
    category: "dsa",
  },
  {
    id: "project-1",
    title: "Push a GitHub Commit",
    description: "Even a README improvement counts. Consistency > perfection.",
    xpReward: 50,
    category: "project",
  },
  {
    id: "interview-1",
    title: "Record Your 60-Second Intro",
    description: "Camera on. Say your name, college, skills, and goal. Watch it back.",
    xpReward: 50,
    category: "interview",
  },
  {
    id: "networking-1",
    title: "Apply to 5 Internships",
    description: "LinkedIn Easy Apply, Internshala, or company careers pages.",
    xpReward: 50,
    category: "networking",
  },
  {
    id: "resume-1",
    title: "Add One Metric to Your Resume",
    description: "Replace 'built a website' with 'built a website serving 500+ users'.",
    xpReward: 50,
    category: "resume",
  },
  {
    id: "dsa-2",
    title: "Explain One System Design Topic",
    description: "Load balancing, caching, or databases. Speak it out loud. To the mirror.",
    xpReward: 50,
    category: "dsa",
  },
  {
    id: "project-2",
    title: "Write a README for Your Best Project",
    description: "Problem, solution, tech stack, demo link. Clean and simple.",
    xpReward: 50,
    category: "project",
  },
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "1",
    author: "Aryan K.",
    college: "IIT KGP",
    title: "How I went from 84 Berojgar Score to Google offer in 4 months",
    replies: 142,
    timeAgo: "2h ago",
    tag: "Success Story",
  },
  {
    id: "2",
    author: "Sneha G.",
    college: "Jadavpur University",
    title: "Resume roasted 3 times — here's what finally worked",
    replies: 89,
    timeAgo: "5h ago",
    tag: "Resume",
  },
  {
    id: "3",
    author: "Dev M.",
    college: "LNCT Bhopal",
    title: "DSA roadmap for non-CS students — no fluff version",
    replies: 201,
    timeAgo: "1d ago",
    tag: "DSA",
  },
  {
    id: "4",
    author: "Meera N.",
    college: "CET Kerala",
    title: "Anyone else applying to Kerala startups? Let's compare notes",
    replies: 34,
    timeAgo: "3h ago",
    tag: "Placement",
  },
  {
    id: "5",
    author: "Vikram D.",
    college: "KIIT",
    title: "Mock interview partner needed — Java/Spring Boot focus",
    replies: 12,
    timeAgo: "6h ago",
    tag: "Buddy",
  },
];

export const COLLEGE_GROUPS = [
  { name: "IIT Alumni", members: 1240, emoji: "" },
  { name: "NIT Network", members: 980, emoji: "" },
  { name: "BITS Grads", members: 720, emoji: "" },
  { name: "VIT Connect", members: 1650, emoji: "" },
  { name: "West Bengal Engineers", members: 2100, emoji: "" },
  { name: "Tamil Nadu Tech", members: 1890, emoji: "" },
  { name: "Maharashtra DEVs", members: 1440, emoji: "" },
  { name: "Tier-3 Warriors", members: 3200, emoji: "" },
];
