export interface TestCase {
  input: string;
  expectedOutput: string;
  description?: string;
}

export interface PostSolutionExplanation {
  dsaUsed: string;
  why: string;
  timeComplexity: string;
  spaceComplexity: string;
  realWorldApplications: string[];
}

export interface RealWorldDSAChallenge {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  category: string;
  dsaConcept: string;
  difficulty: "Easy" | "Medium" | "Hard";
  
  // existing static fields
  realWorldContext?: string;
  problem?: string;
  inputFormat?: string;
  outputFormat?: string;
  constraints?: string;
  dsaObjective?: string;
  starterCode?: Record<number, string>;
  publicTestCases?: TestCase[];
  hiddenTestCases?: TestCase[];
  postSolutionExplanation?: PostSolutionExplanation;

  // external source properties
  source?: "static" | "codeforces";
  url?: string;
  rating?: number;
  tags?: string[];
  solvedCount?: number;
}

export const REAL_WORLD_DSA_CHALLENGES: RealWorldDSAChallenge[] = [
  {
    id: "rwdsa-1",
    slug: "food-delivery-rider-assignment",
    title: "Food Delivery Rider Assignment",
    shortDescription: "Assign the nearest available delivery rider to a new customer food order dynamically.",
    category: "Logistics & Dispatch",
    dsaConcept: "Priority Queue / Heap",
    difficulty: "Medium",
    realWorldContext:
      "At Swiggy/Zomato, when an order is placed at a restaurant, the dispatch engine needs to find the optimal available rider. Riders are rated by distance to restaurant and ETA. Using a min-heap allows the engine to instantly retrieve the best rider in O(1) time and update availability in O(log N) time.",
    problem:
      "Given an array of delivery riders with their IDs and distances (in km) to the restaurant, write a program that selects the closest rider (minimum distance). If two riders have the same distance, select the one with the smaller rider ID.",
    inputFormat: "First line: N (number of riders). Next N lines: rider_id distance",
    outputFormat: "Print the ID of the assigned rider and the distance, formatted as: Assigned Rider: <id> (<distance> km)",
    constraints: "1 <= N <= 10^5, distance >= 0.0",
    dsaObjective:
      "Learn how Priority Queues (Min-Heaps) extract minimum elements efficiently without re-sorting the entire list on every insertion or update.",
    starterCode: {
      71: [
        "# Python 3 Solution - Food Delivery Rider Assignment",
        "import heapq",
        "import sys",
        "",
        "def solve():",
        "    lines = sys.stdin.read().split()",
        "    if not lines:",
        "        return",
        "    n = int(lines[0])",
        "    riders = []",
        "    idx = 1",
        "    for _ in range(n):",
        "        r_id = lines[idx]",
        "        dist = float(lines[idx+1])",
        "        riders.append((dist, r_id))",
        "        idx += 2",
        "    ",
        "    heapq.heapify(riders)",
        "    best_dist, best_id = heapq.heappop(riders)",
        '    print(f"Assigned Rider: {best_id} ({best_dist:.1f} km)")',
        "",
        'if __name__ == "__main__":',
        "    solve()",
      ].join("\n"),
      54: [
        "// C++ Solution - Food Delivery Rider Assignment",
        "#include <iostream>",
        "#include <vector>",
        "#include <queue>",
        "#include <string>",
        "#include <iomanip>",
        "",
        "using namespace std;",
        "",
        "struct Rider {",
        "    string id;",
        "    double dist;",
        "    bool operator>(const Rider& other) const {",
        "        if (dist != other.dist) return dist > other.dist;",
        "        return id > other.id;",
        "    }",
        "};",
        "",
        "int main() {",
        "    int n;",
        "    if (!(cin >> n)) return 0;",
        "    priority_queue<Rider, vector<Rider>, greater<Rider>> minHeap;",
        "    for (int i = 0; i < n; i++) {",
        "        string id;",
        "        double dist;",
        "        cin >> id >> dist;",
        "        minHeap.push({id, dist});",
        "    }",
        "    Rider best = minHeap.top();",
        "    cout << fixed << setprecision(1);",
        '    cout << "Assigned Rider: " << best.id << " (" << best.dist << " km)" << endl;',
        "    return 0;",
        "}",
      ].join("\n"),
      62: [
        "// Java Solution - Food Delivery Rider Assignment",
        "import java.util.*;",
        "",
        "public class Main {",
        "    static class Rider {",
        "        String id;",
        "        double dist;",
        "        Rider(String id, double dist) {",
        "            this.id = id;",
        "            this.dist = dist;",
        "        }",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        Scanner sc = new Scanner(System.in);",
        "        if (!sc.hasNextInt()) return;",
        "        int n = sc.nextInt();",
        "        PriorityQueue<Rider> pq = new PriorityQueue<>((a, b) -> {",
        "            if (a.dist != b.dist) return Double.compare(a.dist, b.dist);",
        "            return a.id.compareTo(b.id);",
        "        });",
        "        for (int i = 0; i < n; i++) {",
        "            String id = sc.next();",
        "            double dist = sc.nextDouble();",
        "            pq.add(new Rider(id, dist));",
        "        }",
        "        Rider best = pq.poll();",
        '        System.out.printf(Locale.US, "Assigned Rider: %s (%.1f km)%n", best.id, best.dist);',
        "    }",
        "}",
      ].join("\n"),
      63: [
        "// JavaScript (Node.js) Solution - Food Delivery Rider Assignment",
        "const fs = require('fs');",
        "",
        "function solve() {",
        "    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);",
        "    if (!input || input.length < 2) return;",
        "    const n = parseInt(input[0]);",
        "    let idx = 1;",
        "    let riders = [];",
        "    for (let i = 0; i < n; i++) {",
        "        const id = input[idx++];",
        "        const dist = parseFloat(input[idx++]);",
        "        riders.push({ id, dist });",
        "    }",
        "    riders.sort((a, b) => a.dist === b.dist ? a.id.localeCompare(b.id) : a.dist - b.dist);",
        "    const best = riders[0];",
        '    console.log("Assigned Rider: " + best.id + " (" + best.dist.toFixed(1) + " km)");',
        "}",
        "",
        "solve();",
      ].join("\n"),
      60: [
        "// Go Solution - Food Delivery Rider Assignment",
        "package main",
        "",
        "import (",
        '	"container/heap"',
        '	"fmt"',
        ")",
        "",
        "type Rider struct {",
        "	id   string",
        "	dist float64",
        "}",
        "",
        "type RiderHeap []Rider",
        "",
        "func (h RiderHeap) Len() int           { return len(h) }",
        "func (h RiderHeap) Less(i, j int) bool {",
        "	if h[i].dist == h[j].dist {",
        "		return h[i].id < h[j].id",
        "	}",
        "	return h[i].dist < h[j].dist",
        "}",
        "func (h RiderHeap) Swap(i, j int)       { h[i], h[j] = h[j], h[i] }",
        "func (h *RiderHeap) Push(x interface{}) { *h = append(*h, x.(Rider)) }",
        "func (h *RiderHeap) Pop() interface{} {",
        "	old := *h",
        "	n := len(old)",
        "	x := old[n-1]",
        "	*h = old[0 : n-1]",
        "	return x",
        "}",
        "",
        "func main() {",
        "	var n int",
        "	if _, err := fmt.Scan(&n); err != nil {",
        "		return",
        "	}",
        "	h := &RiderHeap{}",
        "	heap.Init(h)",
        "	for i := 0; i < n; i++ {",
        "		var id string",
        "		var dist float64",
        "		fmt.Scan(&id, &dist)",
        "		heap.Push(h, Rider{id: id, dist: dist})",
        "	}",
        "	best := heap.Pop(h).(Rider)",
        '	fmt.Printf("Assigned Rider: %s (%.1f km)\\n", best.id, best.dist)',
        "}",
      ].join("\n"),
    },
    publicTestCases: [
      {
        description: "3 nearby riders",
        input: "3\nRIDER_A 4.2\nRIDER_B 1.8\nRIDER_C 3.5",
        expectedOutput: "Assigned Rider: RIDER_B (1.8 km)",
      },
      {
        description: "Riders with equal distance",
        input: "2\nRIDER_X 2.5\nRIDER_M 2.5",
        expectedOutput: "Assigned Rider: RIDER_M (2.5 km)",
      },
    ],
    hiddenTestCases: [
      {
        input: "4\nR1 10.0\nR2 2.1\nR3 0.5\nR4 1.2",
        expectedOutput: "Assigned Rider: R3 (0.5 km)",
      },
    ],
    postSolutionExplanation: {
      dsaUsed: "Priority Queue / Min-Heap",
      why: "In high-throughput dispatch systems (Swiggy, Uber, Blinkit), driver locations and order requests change every millisecond. A Min-Heap guarantees instant O(1) access to the highest-priority rider and log(N) insertion/deletion.",
      timeComplexity: "O(N log N) to insert/heapify, O(1) to peek top priority rider.",
      spaceComplexity: "O(N) to store N rider state pointers in memory.",
      realWorldApplications: [
        "Food delivery rider assignment (Swiggy, Zomato)",
        "Ride-hailing driver matching (Uber, Ola)",
        "Task & job scheduling engines (Celery, Kubernetes OS Schedulers)",
        "Dijkstra's shortest path routing algorithm",
      ],
    },
  },
  {
    id: "rwdsa-2",
    slug: "pharmacy-search",
    title: "Pharmacy Medicine Search",
    shortDescription: "Instant O(1) stock and price lookup for thousands of medicines across pharmacy stores.",
    category: "E-Commerce & Retail",
    dsaConcept: "HashMap / Hash Table",
    difficulty: "Easy",
    realWorldContext:
      "Online pharmacy aggregators (1mg, Apollo 247, Netmeds) handle millions of search queries per minute. To check stock levels and pricing instantly without hitting slow disk databases on every keypress, in-memory Hash Maps are used.",
    problem:
      "Given N medicine records containing name, stock count, and price per unit, process Q search queries for medicine names. Return stock status and price, or 'Not Found'.",
    inputFormat: "First line: N Q. Next N lines: medicine_name stock price. Next Q lines: query_name",
    outputFormat: "For each query, print '<medicine>: Stock <count>, Price $<price>' or '<medicine>: Not Found'",
    constraints: "1 <= N, Q <= 10^5",
    dsaObjective:
      "Understand how key-value hashing enables sub-millisecond lookup times regardless of catalog size.",
    starterCode: {
      71: [
        "# Python 3 Solution - Pharmacy Search",
        "import sys",
        "",
        "def solve():",
        "    lines = sys.stdin.read().split()",
        "    if not lines:",
        "        return",
        "    n = int(lines[0])",
        "    q = int(lines[1])",
        "    ",
        "    inventory = {}",
        "    idx = 2",
        "    for _ in range(n):",
        "        name = lines[idx]",
        "        stock = int(lines[idx+1])",
        "        price = float(lines[idx+2])",
        "        inventory[name.lower()] = (name, stock, price)",
        "        idx += 3",
        "        ",
        "    for _ in range(q):",
        "        query = lines[idx]",
        "        idx += 1",
        "        key = query.lower()",
        "        if key in inventory:",
        "            orig_name, stock, price = inventory[key]",
        '            print(f"{orig_name}: Stock {stock}, Price ${price:.2f}")',
        "        else:",
        '            print(f"{query}: Not Found")',
        "",
        'if __name__ == "__main__":',
        "    solve()",
      ].join("\n"),
      54: [
        "// C++ Solution - Pharmacy Search",
        "#include <iostream>",
        "#include <unordered_map>",
        "#include <string>",
        "#include <algorithm>",
        "#include <iomanip>",
        "",
        "using namespace std;",
        "",
        "struct Med {",
        "    string name;",
        "    int stock;",
        "    double price;",
        "};",
        "",
        "string toLower(string s) {",
        "    for (char &c : s) c = tolower(c);",
        "    return s;",
        "}",
        "",
        "int main() {",
        "    int n, q;",
        "    if (!(cin >> n >> q)) return 0;",
        "    unordered_map<string, Med> inv;",
        "    for (int i = 0; i < n; i++) {",
        "        string name;",
        "        int stock;",
        "        double price;",
        "        cin >> name >> stock >> price;",
        "        inv[toLower(name)] = {name, stock, price};",
        "    }",
        "    cout << fixed << setprecision(2);",
        "    for (int i = 0; i < q; i++) {",
        "        string query;",
        "        cin >> query;",
        "        string key = toLower(query);",
        "        if (inv.count(key)) {",
        "            Med m = inv[key];",
        '            cout << m.name << ": Stock " << m.stock << ", Price $" << m.price << endl;',
        "        } else {",
        '            cout << query << ": Not Found" << endl;',
        "        }",
        "    }",
        "    return 0;",
        "}",
      ].join("\n"),
      62: [
        "// Java Solution - Pharmacy Search",
        "import java.util.*;",
        "",
        "public class Main {",
        "    static class Med {",
        "        String name;",
        "        int stock;",
        "        double price;",
        "        Med(String name, int stock, double price) {",
        "            this.name = name;",
        "            this.stock = stock;",
        "            this.price = price;",
        "        }",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        Scanner sc = new Scanner(System.in);",
        "        if (!sc.hasNextInt()) return;",
        "        int n = sc.nextInt();",
        "        int q = sc.nextInt();",
        "        Map<String, Med> inv = new HashMap<>();",
        "        for (int i = 0; i < n; i++) {",
        "            String name = sc.next();",
        "            int stock = sc.nextInt();",
        "            double price = sc.nextDouble();",
        "            inv.put(name.toLowerCase(), new Med(name, stock, price));",
        "        }",
        "        for (int i = 0; i < q; i++) {",
        "            String query = sc.next();",
        "            Med m = inv.get(query.toLowerCase());",
        "            if (m != null) {",
        '                System.out.printf(Locale.US, "%s: Stock %d, Price $%.2f%n", m.name, m.stock, m.price);',
        "            } else {",
        '                System.out.println(query + ": Not Found");',
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
      63: [
        "// JavaScript (Node.js) Solution - Pharmacy Search",
        "const fs = require('fs');",
        "",
        "function solve() {",
        "    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);",
        "    if (!input || input.length < 2) return;",
        "    const n = parseInt(input[0]);",
        "    const q = parseInt(input[1]);",
        "    let idx = 2;",
        "    const inv = new Map();",
        "    for (let i = 0; i < n; i++) {",
        "        const name = input[idx++];",
        "        const stock = parseInt(input[idx++]);",
        "        const price = parseFloat(input[idx++]);",
        "        inv.set(name.toLowerCase(), { name, stock, price });",
        "    }",
        "    for (let i = 0; i < q; i++) {",
        "        const query = input[idx++];",
        "        if (!query) break;",
        "        const m = inv.get(query.toLowerCase());",
        "        if (m) {",
        '            console.log(m.name + ": Stock " + m.stock + ", Price $" + m.price.toFixed(2));',
        "        } else {",
        '            console.log(query + ": Not Found");',
        "        }",
        "    }",
        "}",
        "",
        "solve();",
      ].join("\n"),
      60: [
        "// Go Solution - Pharmacy Search",
        "package main",
        "",
        "import (",
        '	"fmt"',
        '	"strings"',
        ")",
        "",
        "type Med struct {",
        "	name  string",
        "	stock int",
        "	price float64",
        "}",
        "",
        "func main() {",
        "	var n, q int",
        "	if _, err := fmt.Scan(&n, &q); err != nil {",
        "		return",
        "	}",
        "	inv := make(map[string]Med)",
        "	for i := 0; i < n; i++ {",
        "		var name string",
        "		var stock int",
        "		var price float64",
        "		fmt.Scan(&name, &stock, &price)",
        "		inv[strings.ToLower(name)] = Med{name: name, stock: stock, price: price}",
        "	}",
        "	for i := 0; i < q; i++ {",
        "		var query string",
        "		fmt.Scan(&query)",
        "		if m, ok := inv[strings.ToLower(query)]; ok {",
        '			fmt.Printf("%s: Stock %d, Price $%.2f\\n", m.name, m.stock, m.price)',
        "		} else {",
        '			fmt.Printf("%s: Not Found\\n", query)',
        "		}",
        "	}",
        "}",
      ].join("\n"),
    },
    publicTestCases: [
      {
        description: "2 medicines, 2 queries",
        input: "2 2\nParacetamol 100 15.50\nCrocin 50 20.00\nParacetamol\nDispirin",
        expectedOutput: "Paracetamol: Stock 100, Price $15.50\nDispirin: Not Found",
      },
    ],
    hiddenTestCases: [
      {
        input: "3 1\nAmoxicillin 25 120.00\nAzithromycin 10 250.00\nVitaminC 200 5.00\nVitaminC",
        expectedOutput: "VitaminC: Stock 200, Price $5.00",
      },
    ],
    postSolutionExplanation: {
      dsaUsed: "Hash Table / HashMap",
      why: "A Hash Table maps keys to memory locations using a hash function. This allows instant O(1) average lookup time regardless of whether your catalog has 100 items or 10,000,000 items.",
      timeComplexity: "O(1) average time per lookup, O(N) total time for input loading.",
      spaceComplexity: "O(N) space for hash table entries.",
      realWorldApplications: [
        "In-memory caches (Redis, Memcached)",
        "Database indexing & primary key lookups",
        "E-commerce product inventory search",
        "API rate limiters & session state stores",
      ],
    },
  },
  {
    id: "rwdsa-3",
    slug: "navigation-route-finder",
    title: "Navigation & Route Finder",
    shortDescription: "Calculate the shortest delivery path and travel time across a network of city intersections.",
    category: "Maps & Routing",
    dsaConcept: "Graph + Dijkstra's Algorithm",
    difficulty: "Hard",
    realWorldContext:
      "Google Maps and Rapido represent road networks as weighted directed graphs where nodes are intersections and edges are road segments weighted by traffic travel time. Dijkstra's Algorithm finds the fastest route from restaurant to customer.",
    problem:
      "Given N nodes (intersections) and M weighted road connections (source, destination, time_minutes), find the shortest time path from start node S to destination node T.",
    inputFormat: "First line: N M S T. Next M lines: u v w (road from u to v with time w)",
    outputFormat: "Print 'Fastest Time: <time> mins' or 'Unreachable'",
    constraints: "1 <= N <= 10^4, 1 <= M <= 10^5, weight >= 1",
    dsaObjective:
      "Master graph traversal and greedy shortest path estimation using Dijkstra's Algorithm.",
    starterCode: {
      71: [
        "# Python 3 Solution - Navigation / Dijkstra Route Finder",
        "import heapq",
        "import sys",
        "",
        "def solve():",
        "    lines = sys.stdin.read().split()",
        "    if not lines:",
        "        return",
        "    n = int(lines[0])",
        "    m = int(lines[1])",
        "    start = int(lines[2])",
        "    target = int(lines[3])",
        "    ",
        "    adj = [[] for _ in range(n + 1)]",
        "    idx = 4",
        "    for _ in range(m):",
        "        u = int(lines[idx])",
        "        v = int(lines[idx+1])",
        "        w = int(lines[idx+2])",
        "        adj[u].append((v, w))",
        "        idx += 3",
        "        ",
        "    dist = [float('inf')] * (n + 1)",
        "    dist[start] = 0",
        "    pq = [(0, start)]",
        "    ",
        "    while pq:",
        "        d, u = heapq.heappop(pq)",
        "        if d > dist[u]:",
        "            continue",
        "        if u == target:",
        "            break",
        "        for v, w in adj[u]:",
        "            if dist[u] + w < dist[v]:",
        "                dist[v] = dist[u] + w",
        "                heapq.heappush(pq, (dist[v], v))",
        "                ",
        "    if dist[target] == float('inf'):",
        '        print("Unreachable")',
        "    else:",
        '        print(f"Fastest Time: {int(dist[target])} mins")',
        "",
        'if __name__ == "__main__":',
        "    solve()",
      ].join("\n"),
      54: [
        "// C++ Solution - Navigation / Dijkstra Route Finder",
        "#include <iostream>",
        "#include <vector>",
        "#include <queue>",
        "",
        "using namespace std;",
        "",
        "const int INF = 1e9;",
        "",
        "int main() {",
        "    int n, m, start, target;",
        "    if (!(cin >> n >> m >> start >> target)) return 0;",
        "    vector<vector<pair<int, int>>> adj(n + 1);",
        "    for (int i = 0; i < m; i++) {",
        "        int u, v, w;",
        "        cin >> u >> v >> w;",
        "        adj[u].push_back({v, w});",
        "    }",
        "    vector<int> dist(n + 1, INF);",
        "    dist[start] = 0;",
        "    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;",
        "    pq.push({0, start});",
        "    while (!pq.empty()) {",
        "        auto curr = pq.top();",
        "        int d = curr.first;",
        "        int u = curr.second;",
        "        pq.pop();",
        "        if (d > dist[u]) continue;",
        "        if (u == target) break;",
        "        for (auto& edge : adj[u]) {",
        "            int v = edge.first, w = edge.second;",
        "            if (dist[u] + w < dist[v]) {",
        "                dist[v] = dist[u] + w;",
        "                pq.push({dist[v], v});",
        "            }",
        "        }",
        "    }",
        "    if (dist[target] == INF) {",
        '        cout << "Unreachable" << endl;',
        "    } else {",
        '        cout << "Fastest Time: " << dist[target] << " mins" << endl;',
        "    }",
        "    return 0;",
        "}",
      ].join("\n"),
      62: [
        "// Java Solution - Navigation / Dijkstra Route Finder",
        "import java.util.*;",
        "",
        "public class Main {",
        "    static class Edge {",
        "        int v, w;",
        "        Edge(int v, int w) { this.v = v; this.w = w; }",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        Scanner sc = new Scanner(System.in);",
        "        if (!sc.hasNextInt()) return;",
        "        int n = sc.nextInt();",
        "        int m = sc.nextInt();",
        "        int start = sc.nextInt();",
        "        int target = sc.nextInt();",
        "",
        "        List<List<Edge>> adj = new ArrayList<>();",
        "        for (int i = 0; i <= n; i++) adj.add(new ArrayList<>());",
        "        for (int i = 0; i < m; i++) {",
        "            int u = sc.nextInt();",
        "            int v = sc.nextInt();",
        "            int w = sc.nextInt();",
        "            adj.get(u).add(new Edge(v, w));",
        "        }",
        "",
        "        int[] dist = new int[n + 1];",
        "        Arrays.fill(dist, Integer.MAX_VALUE);",
        "        dist[start] = 0;",
        "        PriorityQueue<int[]> pq = new PriorityQueue<>((a, b) -> a[0] - b[0]);",
        "        pq.add(new int[]{0, start});",
        "",
        "        while (!pq.isEmpty()) {",
        "            int[] curr = pq.poll();",
        "            int d = curr[0], u = curr[1];",
        "            if (d > dist[u]) continue;",
        "            if (u == target) break;",
        "            for (Edge e : adj.get(u)) {",
        "                if (dist[u] + e.w < dist[e.v]) {",
        "                    dist[e.v] = dist[u] + e.w;",
        "                    pq.add(new int[]{dist[e.v], e.v});",
        "                }",
        "            }",
        "        }",
        "",
        "        if (dist[target] == Integer.MAX_VALUE) {",
        '            System.out.println("Unreachable");',
        "        } else {",
        '            System.out.println("Fastest Time: " + dist[target] + " mins");',
        "        }",
        "    }",
        "}",
      ].join("\n"),
      63: [
        "// JavaScript (Node.js) Solution - Navigation / Dijkstra Route Finder",
        "const fs = require('fs');",
        "",
        "function solve() {",
        "    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);",
        "    if (!input || input.length < 4) return;",
        "    const n = parseInt(input[0]);",
        "    const m = parseInt(input[1]);",
        "    const start = parseInt(input[2]);",
        "    const target = parseInt(input[3]);",
        "",
        "    const adj = Array.from({ length: n + 1 }, () => []);",
        "    let idx = 4;",
        "    for (let i = 0; i < m; i++) {",
        "        const u = parseInt(input[idx++]);",
        "        const v = parseInt(input[idx++]);",
        "        const w = parseInt(input[idx++]);",
        "        adj[u].push({ v, w });",
        "    }",
        "",
        "    const dist = Array(n + 1).fill(Infinity);",
        "    dist[start] = 0;",
        "    const visited = Array(n + 1).fill(false);",
        "",
        "    for (let i = 0; i < n; i++) {",
        "        let u = -1;",
        "        for (let j = 1; j <= n; j++) {",
        "            if (!visited[j] && (u === -1 || dist[j] < dist[u])) {",
        "                u = j;",
        "            }",
        "        }",
        "        if (u === -1 || dist[u] === Infinity) break;",
        "        visited[u] = true;",
        "        if (u === target) break;",
        "",
        "        for (const edge of adj[u]) {",
        "            if (dist[u] + edge.w < dist[edge.v]) {",
        "                dist[edge.v] = dist[u] + edge.w;",
        "            }",
        "        }",
        "    }",
        "",
        "    if (dist[target] === Infinity) {",
        '        console.log("Unreachable");',
        "    } else {",
        '        console.log("Fastest Time: " + dist[target] + " mins");',
        "    }",
        "}",
        "",
        "solve();",
      ].join("\n"),
      60: [
        "// Go Solution - Navigation / Dijkstra Route Finder",
        "package main",
        "",
        "import (",
        '	"container/heap"',
        '	"fmt"',
        ")",
        "",
        "type Item struct {",
        "	dist int",
        "	u    int",
        "}",
        "",
        "type PQ []Item",
        "",
        "func (pq PQ) Len() int           { return len(pq) }",
        "func (pq PQ) Less(i, j int) bool { return pq[i].dist < pq[j].dist }",
        "func (pq PQ) Swap(i, j int)      { pq[i], pq[j] = pq[j], pq[i] }",
        "func (pq *PQ) Push(x interface{}) {",
        "	*pq = append(*pq, x.(Item))",
        "}",
        "func (pq *PQ) Pop() interface{} {",
        "	old := *pq",
        "	n := len(old)",
        "	item := old[n-1]",
        "	*pq = old[0 : n-1]",
        "	return item",
        "}",
        "",
        "func main() {",
        "	var n, m, start, target int",
        "	if _, err := fmt.Scan(&n, &m, &start, &target); err != nil {",
        "		return",
        "	}",
        "	type Edge struct{ v, w int }",
        "	adj := make([][]Edge, n+1)",
        "	for i := 0; i < m; i++ {",
        "		var u, v, w int",
        "		fmt.Scan(&u, &v, &w)",
        "		adj[u] = append(adj[u], Edge{v: v, w: w})",
        "	}",
        "	dist := make([]int, n+1)",
        "	for i := range dist {",
        "		dist[i] = 1e9",
        "	}",
        "	dist[start] = 0",
        "	pq := &PQ{}",
        "	heap.Init(pq)",
        "	heap.Push(pq, Item{dist: 0, u: start})",
        "",
        "	for pq.Len() > 0 {",
        "		curr := heap.Pop(pq).(Item)",
        "		d, u := curr.dist, curr.u",
        "		if d > dist[u] {",
        "			continue",
        "		}",
        "		if u == target {",
        "			break",
        "		}",
        "		for _, e := range adj[u] {",
        "			if dist[u]+e.w < dist[e.v] {",
        "				dist[e.v] = dist[u] + e.w",
        "				heap.Push(pq, Item{dist: dist[e.v], u: e.v})",
        "			}",
        "        }",
        "	}",
        "	if dist[target] == 1e9 {",
        '		fmt.Println("Unreachable")',
        "	} else {",
        '		fmt.Printf("Fastest Time: %d mins\\n", dist[target])',
        "	}",
        "}",
      ].join("\n"),
    },
    publicTestCases: [
      {
        description: "Direct & indirect paths",
        input: "4 4 1 4\n1 2 5\n2 4 10\n1 3 2\n3 4 4",
        expectedOutput: "Fastest Time: 6 mins",
      },
    ],
    hiddenTestCases: [
      {
        input: "3 1 1 3\n1 2 4",
        expectedOutput: "Unreachable",
      },
    ],
    postSolutionExplanation: {
      dsaUsed: "Graph + Dijkstra's Shortest Path Algorithm",
      why: "Dijkstra's Algorithm iteratively relaxes edges using a Priority Queue, finding the guaranteed shortest route in O((V + E) log V) time instead of blindly testing exponentially many paths.",
      timeComplexity: "O((V + E) log V) where V = nodes (intersections), E = edges (roads).",
      spaceComplexity: "O(V + E) space to store adjacency list and distance vector.",
      realWorldApplications: [
        "GPS Navigation & Map routing engines (Google Maps, Waze)",
        "Network packet routing (IP protocol & open shortest path first OSPF)",
        "Logistics & supply chain vehicle route planning",
        "Flight path estimation & airline scheduling",
      ],
    },
  },
  {
    id: "rwdsa-4",
    slug: "autocomplete-search",
    title: "Autocomplete Search Suggestions",
    shortDescription: "Build real-time search box suggestions using prefix matching over dictionary words.",
    category: "Search & NLP",
    dsaConcept: "Trie (Prefix Tree)",
    difficulty: "Medium",
    realWorldContext:
      "When typing in Google or Amazon, suggestions appear within milliseconds. Scanning millions of strings with standard array filters is too slow. A Trie (Prefix Tree) organizes words character by character, allowing O(L) prefix lookups where L is query length.",
    problem:
      "Given a list of N dictionary words, insert them into a Trie. Then process Q prefix queries. For each prefix query, print all dictionary words that start with that prefix in alphabetical order, separated by commas. If none match, print 'No suggestions'.",
    inputFormat: "First line: N Q. Next N lines: dictionary_words. Next Q lines: prefix_queries",
    outputFormat: "Print 'Suggestions for \"<prefix>\": <word1>, <word2>' or 'Suggestions for \"<prefix>\": No suggestions'",
    constraints: "1 <= N <= 1000, 1 <= Q <= 100",
    dsaObjective:
      "Learn how Prefix Trees (Tries) share common prefixes across words to dramatically optimize search suggestions.",
    starterCode: {
      71: [
        "# Python 3 Solution - Autocomplete Trie",
        "import sys",
        "",
        "class TrieNode:",
        "    def __init__(self):",
        "        self.children = {}",
        "        self.is_end = False",
        "",
        "class Trie:",
        "    def __init__(self):",
        "        self.root = TrieNode()",
        "",
        "    def insert(self, word):",
        "        node = self.root",
        "        for char in word:",
        "            if char not in node.children:",
        "                node.children[char] = TrieNode()",
        "            node = node.children[char]",
        "        node.is_end = True",
        "",
        "    def find_words_with_prefix(self, prefix):",
        "        node = self.root",
        "        for char in prefix:",
        "            if char not in node.children:",
        "                return []",
        "            node = node.children[char]",
        "        ",
        "        results = []",
        "        def dfs(curr, path):",
        "            if curr.is_end:",
        "                results.append(path)",
        "            for char in sorted(curr.children.keys()):",
        "                dfs(curr.children[char], path + char)",
        "",
        "        dfs(node, prefix)",
        "        return results",
        "",
        "def solve():",
        "    lines = sys.stdin.read().split()",
        "    if not lines:",
        "        return",
        "    n = int(lines[0])",
        "    q = int(lines[1])",
        "    trie = Trie()",
        "    idx = 2",
        "    for _ in range(n):",
        "        trie.insert(lines[idx])",
        "        idx += 1",
        "    for _ in range(q):",
        "        prefix = lines[idx]",
        "        idx += 1",
        "        matches = trie.find_words_with_prefix(prefix)",
        "        if matches:",
        '            print(f\'Suggestions for "{prefix}": {\", \".join(matches)}\')',
        "        else:",
        '            print(f\'Suggestions for "{prefix}": No suggestions\')',
        "",
        'if __name__ == "__main__":',
        "    solve()",
      ].join("\n"),
      54: [
        "// C++ Solution - Autocomplete Trie",
        "#include <iostream>",
        "#include <vector>",
        "#include <map>",
        "#include <string>",
        "#include <algorithm>",
        "",
        "using namespace std;",
        "",
        "struct TrieNode {",
        "    map<char, TrieNode*> children;",
        "    bool isEnd = false;",
        "};",
        "",
        "class Trie {",
        "    TrieNode* root;",
        "    void dfs(TrieNode* curr, string path, vector<string>& res) {",
        "        if (curr->isEnd) res.push_back(path);",
        "        for (auto& p : curr->children) {",
        "            dfs(p.second, path + p.first, res);",
        "        }",
        "    }",
        "public:",
        "    Trie() { root = new TrieNode(); }",
        "    void insert(string word) {",
        "        TrieNode* curr = root;",
        "        for (char c : word) {",
        "            if (!curr->children.count(c)) curr->children[c] = new TrieNode();",
        "            curr = curr->children[c];",
        "        }",
        "        curr->isEnd = true;",
        "    }",
        "    vector<string> searchPrefix(string prefix) {",
        "        TrieNode* curr = root;",
        "        vector<string> res;",
        "        for (char c : prefix) {",
        "            if (!curr->children.count(c)) return res;",
        "            curr = curr->children[c];",
        "        }",
        "        dfs(curr, prefix, res);",
        "        return res;",
        "    }",
        "};",
        "",
        "int main() {",
        "    int n, q;",
        "    if (!(cin >> n >> q)) return 0;",
        "    Trie trie;",
        "    for (int i = 0; i < n; i++) {",
        "        string w;",
        "        cin >> w;",
        "        trie.insert(w);",
        "    }",
        "    for (int i = 0; i < q; i++) {",
        "        string pref;",
        "        cin >> pref;",
        "        auto matches = trie.searchPrefix(pref);",
        '        cout << "Suggestions for \\"" << pref << "\\": ";',
        "        if (matches.empty()) {",
        '            cout << "No suggestions" << endl;',
        "        } else {",
        "            for (size_t k = 0; k < matches.size(); k++) {",
        '                cout << matches[k] << (k + 1 == matches.size() ? "" : ", ");',
        "            }",
        "            cout << endl;",
        "        }",
        "    }",
        "    return 0;",
        "}",
      ].join("\n"),
      62: [
        "// Java Solution - Autocomplete Trie",
        "import java.util.*;",
        "",
        "public class Main {",
        "    static class TrieNode {",
        "        Map<Character, TrieNode> children = new TreeMap<>();",
        "        boolean isEnd = false;",
        "    }",
        "",
        "    static class Trie {",
        "        TrieNode root = new TrieNode();",
        "",
        "        void insert(String word) {",
        "            TrieNode curr = root;",
        "            for (char c : word.toCharArray()) {",
        "                curr.children.putIfAbsent(c, new TrieNode());",
        "                curr = curr.children.get(c);",
        "            }",
        "            curr.isEnd = true;",
        "        }",
        "",
        "        List<String> getSuggestions(String prefix) {",
        "            TrieNode curr = root;",
        "            List<String> res = new ArrayList<>();",
        "            for (char c : prefix.toCharArray()) {",
        "                if (!curr.children.containsKey(c)) return res;",
        "                curr = curr.children.get(c);",
        "            }",
        "            dfs(curr, prefix, res);",
        "            return res;",
        "        }",
        "",
        "        private void dfs(TrieNode curr, String path, List<String> res) {",
        "            if (curr.isEnd) res.add(path);",
        "            for (Map.Entry<Character, TrieNode> entry : curr.children.entrySet()) {",
        "                dfs(entry.getValue(), path + entry.getKey(), res);",
        "            }",
        "        }",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        Scanner sc = new Scanner(System.in);",
        "        if (!sc.hasNextInt()) return;",
        "        int n = sc.nextInt();",
        "        int q = sc.nextInt();",
        "        Trie trie = new Trie();",
        "        for (int i = 0; i < n; i++) trie.insert(sc.next());",
        "        for (int i = 0; i < q; i++) {",
        "            String pref = sc.next();",
        "            List<String> matches = trie.getSuggestions(pref);",
        "            if (matches.isEmpty()) {",
        '                System.out.println("Suggestions for \\"" + pref + "\\": No suggestions");',
        "            } else {",
        '                System.out.println("Suggestions for \\"" + pref + "\\": " + String.join(", ", matches));',
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
      63: [
        "// JavaScript (Node.js) Solution - Autocomplete Trie",
        "const fs = require('fs');",
        "",
        "class TrieNode {",
        "    constructor() {",
        "        this.children = {};",
        "        this.isEnd = false;",
        "    }",
        "}",
        "",
        "class Trie {",
        "    constructor() {",
        "        this.root = new TrieNode();",
        "    }",
        "    insert(word) {",
        "        let node = this.root;",
        "        for (const c of word) {",
        "            if (!node.children[c]) node.children[c] = new TrieNode();",
        "            node = node.children[c];",
        "        }",
        "        node.isEnd = true;",
        "    }",
        "    findPrefix(prefix) {",
        "        let node = this.root;",
        "        for (const c of prefix) {",
        "            if (!node.children[c]) return [];",
        "            node = node.children[c];",
        "        }",
        "        const results = [];",
        "        const dfs = (curr, path) => {",
        "            if (curr.isEnd) results.push(path);",
        "            const keys = Object.keys(curr.children).sort();",
        "            for (const k of keys) dfs(curr.children[k], path + k);",
        "        };",
        "        dfs(node, prefix);",
        "        return results;",
        "    }",
        "}",
        "",
        "function solve() {",
        "    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);",
        "    if (!input || input.length < 2) return;",
        "    const n = parseInt(input[0]);",
        "    const q = parseInt(input[1]);",
        "    const trie = new Trie();",
        "    let idx = 2;",
        "    for (let i = 0; i < n; i++) trie.insert(input[idx++]);",
        "    for (let i = 0; i < q; i++) {",
        "        const pref = input[idx++];",
        "        const matches = trie.findPrefix(pref);",
        "        if (matches.length > 0) {",
        '            console.log("Suggestions for \\"" + pref + "\\": " + matches.join(\', \'));',
        "        } else {",
        '            console.log("Suggestions for \\"" + pref + "\\": No suggestions");',
        "        }",
        "    }",
        "}",
        "",
        "solve();",
      ].join("\n"),
      60: [
        "// Go Solution - Autocomplete Trie",
        "package main",
        "",
        "import (",
        '	"fmt"',
        '	"sort"',
        '	"strings"',
        ")",
        "",
        "type TrieNode struct {",
        "	children map[rune]*TrieNode",
        "	isEnd    bool",
        "}",
        "",
        "type Trie struct {",
        "	root *TrieNode",
        "}",
        "",
        "func NewTrie() *Trie {",
        "	return &Trie{root: &TrieNode{children: make(map[rune]*TrieNode)}}",
        "}",
        "",
        "func (t *Trie) Insert(word string) {",
        "	curr := t.root",
        "	for _, c := range word {",
        "		if _, ok := curr.children[c]; !ok {",
        "			curr.children[c] = &TrieNode{children: make(map[rune]*TrieNode)}",
        "		}",
        "		curr = curr.children[c]",
        "	}",
        "	curr.isEnd = true",
        "}",
        "",
        "func (t *Trie) Search(prefix string) []string {",
        "	curr := t.root",
        "	for _, c := range prefix {",
        "		if next, ok := curr.children[c]; ok {",
        "			curr = next",
        "		} else {",
        "			return nil",
        "		}",
        "	}",
        "	var res []string",
        "	var dfs func(node *TrieNode, path string)",
        "	dfs = func(node *TrieNode, path string) {",
        "		if node.isEnd {",
        "			res = append(res, path)",
        "		}",
        "		var keys []rune",
        "		for k := range node.children {",
        "			keys = append(keys, k)",
        "		}",
        "		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })",
        "		for _, k := range keys {",
        "			dfs(node.children[k], path+string(k))",
        "		}",
        "	}",
        "	dfs(curr, prefix)",
        "	return res",
        "}",
        "",
        "func main() {",
        "	var n, q int",
        "	if _, err := fmt.Scan(&n, &q); err != nil {",
        "		return",
        "	}",
        "	trie := NewTrie()",
        "	for i := 0; i < n; i++ {",
        "		var w string",
        "		fmt.Scan(&w)",
        "		trie.Insert(w)",
        "	}",
        "	for i := 0; i < q; i++ {",
        "		var pref string",
        "		fmt.Scan(&pref)",
        "		matches := trie.Search(pref)",
        "		if len(matches) > 0 {",
        '			fmt.Printf("Suggestions for \\"%s\\": %s\\n", pref, strings.Join(matches, ", "))',
        "		} else {",
        '			fmt.Printf("Suggestions for \\"%s\\": No suggestions\\n", pref)',
        "		}",
        "	}",
        "}",
      ].join("\n"),
    },
    publicTestCases: [
      {
        description: "Search prefix 'app'",
        input: "4 2\napple\napp\napplication\nbanana\napp\nban",
        expectedOutput: 'Suggestions for "app": app, apple, application\nSuggestions for "ban": banana',
      },
    ],
    hiddenTestCases: [
      {
        input: "2 1\ncode\ncoder\nxyz",
        expectedOutput: 'Suggestions for "xyz": No suggestions',
      },
    ],
    postSolutionExplanation: {
      dsaUsed: "Trie (Prefix Tree)",
      why: "A Trie organizes character nodes hierarchically, allowing prefix searches to take O(L) time where L is string length, completely independent of the 1,000,000+ words stored in the dictionary.",
      timeComplexity: "O(L) time for prefix lookup + O(K) where K is number of matching suggestions.",
      spaceComplexity: "O(N * L) total nodes across stored vocabulary.",
      realWorldApplications: [
        "Google & Amazon real-time search box suggestions",
        "Mobile phone keyboard predictive auto-correct (T9 / Swipe)",
        "IP router longest prefix matching table",
        "Spell checker & dictionary lookup tools",
      ],
    },
  },
  {
    id: "rwdsa-5",
    slug: "lru-cache-recently-viewed",
    title: "Recently Viewed Products (LRU Cache)",
    shortDescription: "Design a Least Recently Used (LRU) cache for fast product retrieval with fixed memory capacity.",
    category: "System Design & Memory",
    dsaConcept: "LRU Cache (Doubly Linked List + HashMap)",
    difficulty: "Hard",
    realWorldContext:
      "E-commerce apps (Flipkart, Amazon) display a user's 'Recently Viewed Products'. To keep memory overhead bounded while making accesses and evictions blazingly fast in O(1) time, an LRU Cache is implemented using a HashMap paired with a Doubly Linked List.",
    problem:
      "Implement an LRU Cache with capacity C. Process N operations: 'VIEW product_id' (access product) or 'GET product_id' (retrieve product). Print the product_id if found, else -1. When capacity is exceeded, evict the least recently used product.",
    inputFormat: "First line: Capacity C, Operations N. Next N lines: VIEW <id> or GET <id>",
    outputFormat: "For GET operations, print '<id>' or '-1'",
    constraints: "1 <= C <= 1000, 1 <= N <= 5000",
    dsaObjective:
      "Understand how combining a HashMap with a Doubly Linked List achieves O(1) operations for both lookup and ordering updates.",
    starterCode: {
      71: [
        "# Python 3 Solution - LRU Cache",
        "import sys",
        "",
        "class Node:",
        "    def __init__(self, key=0, val=0):",
        "        self.key = key",
        "        self.val = val",
        "        self.prev = None",
        "        self.next = None",
        "",
        "class LRUCache:",
        "    def __init__(self, capacity: int):",
        "        self.cap = capacity",
        "        self.cache = {}",
        "        self.head = Node()",
        "        self.tail = Node()",
        "        self.head.next = self.tail",
        "        self.tail.prev = self.head",
        "",
        "    def _remove(self, node):",
        "        prev = node.prev",
        "        nxt = node.next",
        "        prev.next = nxt",
        "        nxt.prev = prev",
        "",
        "    def _add_to_head(self, node):",
        "        node.next = self.head.next",
        "        node.prev = self.head",
        "        self.head.next.prev = node",
        "        self.head.next = node",
        "",
        "    def get(self, key: int) -> int:",
        "        if key in self.cache:",
        "            node = self.cache[key]",
        "            self._remove(node)",
        "            self._add_to_head(node)",
        "            return node.val",
        "        return -1",
        "",
        "    def put(self, key: int, value: int):",
        "        if key in self.cache:",
        "            self._remove(self.cache[key])",
        "        node = Node(key, value)",
        "        self.cache[key] = node",
        "        self._add_to_head(node)",
        "        if len(self.cache) > self.cap:",
        "            lru = self.tail.prev",
        "            self._remove(lru)",
        "            del self.cache[lru.key]",
        "",
        "def solve():",
        "    lines = sys.stdin.read().split()",
        "    if not lines:",
        "        return",
        "    cap = int(lines[0])",
        "    n = int(lines[1])",
        "    cache = LRUCache(cap)",
        "    idx = 2",
        "    for _ in range(n):",
        "        op = lines[idx]",
        "        val = int(lines[idx+1])",
        "        idx += 2",
        '        if op == "VIEW":',
        "            cache.put(val, val)",
        '        elif op == "GET":',
        "            res = cache.get(val)",
        "            print(res)",
        "",
        'if __name__ == "__main__":',
        "    solve()",
      ].join("\n"),
      54: [
        "// C++ Solution - LRU Cache",
        "#include <iostream>",
        "#include <unordered_map>",
        "#include <list>",
        "#include <string>",
        "",
        "using namespace std;",
        "",
        "class LRUCache {",
        "    int cap;",
        "    list<pair<int, int>> l;",
        "    unordered_map<int, list<pair<int, int>>::iterator> m;",
        "public:",
        "    LRUCache(int capacity) : cap(capacity) {}",
        "    ",
        "    int get(int key) {",
        "        if (!m.count(key)) return -1;",
        "        l.splice(l.begin(), l, m[key]);",
        "        return m[key]->second;",
        "    }",
        "    ",
        "    void put(int key, int val) {",
        "        if (m.count(key)) {",
        "            l.splice(l.begin(), l, m[key]);",
        "            m[key]->second = val;",
        "            return;",
        "        }",
        "        if (l.size() == cap) {",
        "            int d_key = l.back().first;",
        "            l.pop_back();",
        "            m.erase(d_key);",
        "        }",
        "        l.push_front({key, val});",
        "        m[key] = l.begin();",
        "    }",
        "};",
        "",
        "int main() {",
        "    int cap, n;",
        "    if (!(cin >> cap >> n)) return 0;",
        "    LRUCache cache(cap);",
        "    for (int i = 0; i < n; i++) {",
        "        string op;",
        "        int val;",
        "        cin >> op >> val;",
        '        if (op == "VIEW") {',
        "            cache.put(val, val);",
        '        } else if (op == "GET") {',
        "            cout << cache.get(val) << endl;",
        "        }",
        "    }",
        "    return 0;",
        "}",
      ].join("\n"),
      62: [
        "// Java Solution - LRU Cache",
        "import java.util.*;",
        "",
        "public class Main {",
        "    static class LRUCache {",
        "        int cap;",
        "        LinkedHashMap<Integer, Integer> map;",
        "",
        "        LRUCache(int capacity) {",
        "            this.cap = capacity;",
        "            this.map = new LinkedHashMap<Integer, Integer>(capacity, 0.75f, true) {",
        "                protected boolean removeEldestEntry(Map.Entry<Integer, Integer> eldest) {",
        "                    return size() > cap;",
        "                }",
        "            };",
        "        }",
        "",
        "        int get(int key) {",
        "            return map.getOrDefault(key, -1);",
        "        }",
        "",
        "        void put(int key, int val) {",
        "            map.put(key, val);",
        "        }",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        Scanner sc = new Scanner(System.in);",
        "        if (!sc.hasNextInt()) return;",
        "        int cap = sc.nextInt();",
        "        int n = sc.nextInt();",
        "        LRUCache cache = new LRUCache(cap);",
        "        for (int i = 0; i < n; i++) {",
        "            String op = sc.next();",
        "            int val = sc.nextInt();",
        '            if (op.equals("VIEW")) {',
        "                cache.put(val, val);",
        '            } else if (op.equals("GET")) {',
        "                System.out.println(cache.get(val));",
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
      63: [
        "// JavaScript (Node.js) Solution - LRU Cache",
        "const fs = require('fs');",
        "",
        "class LRUCache {",
        "    constructor(capacity) {",
        "        this.capacity = capacity;",
        "        this.map = new Map();",
        "    }",
        "    get(key) {",
        "        if (!this.map.has(key)) return -1;",
        "        const val = this.map.get(key);",
        "        this.map.delete(key);",
        "        this.map.set(key, val);",
        "        return val;",
        "    }",
        "    put(key, value) {",
        "        if (this.map.has(key)) {",
        "            this.map.delete(key);",
        "        } else if (this.map.size >= this.capacity) {",
        "            const firstKey = this.map.keys().next().value;",
        "            this.map.delete(firstKey);",
        "        }",
        "        this.map.set(key, value);",
        "    }",
        "}",
        "",
        "function solve() {",
        "    const input = fs.readFileSync(0, 'utf-8').trim().split(/\\s+/);",
        "    if (!input || input.length < 2) return;",
        "    const cap = parseInt(input[0]);",
        "    const n = parseInt(input[1]);",
        "    const cache = new LRUCache(cap);",
        "    let idx = 2;",
        "    for (let i = 0; i < n; i++) {",
        "        const op = input[idx++];",
        "        const val = parseInt(input[idx++]);",
        '        if (op === "VIEW") {',
        "            cache.put(val, val);",
        '        } else if (op === "GET") {',
        "            console.log(cache.get(val));",
        "        }",
        "    }",
        "}",
        "",
        "solve();",
      ].join("\n"),
      60: [
        "// Go Solution - LRU Cache",
        "package main",
        "",
        "import (",
        '	"container/list"',
        '	"fmt"',
        ")",
        "",
        "type entry struct {",
        "	key, val int",
        "}",
        "",
        "type LRUCache struct {",
        "	cap int",
        "	l   *list.List",
        "	m   map[int]*list.Element",
        "}",
        "",
        "func NewLRUCache(capacity int) *LRUCache {",
        "	return &LRUCache{",
        "		cap: capacity,",
        "		l:   list.New(),",
        "		m:   make(map[int]*list.Element),",
        "	}",
        "}",
        "",
        "func (c *LRUCache) Get(key int) int {",
        "	if elem, ok := c.m[key]; ok {",
        "		c.l.MoveToFront(elem)",
        "		return elem.Value.(*entry).val",
        "	}",
        "	return -1",
        "}",
        "",
        "func (c *LRUCache) Put(key, val int) {",
        "	if elem, ok := c.m[key]; ok {",
        "		c.l.MoveToFront(elem)",
        "		elem.Value.(*entry).val = val",
        "		return",
        "	}",
        "	if c.l.Len() == c.cap {",
        "		oldest := c.l.Back()",
        "		if oldest != nil {",
        "			c.l.Remove(oldest)",
        "			delete(c.m, oldest.Value.(*entry).key)",
        "		}",
        "	}",
        "	elem := c.l.PushFront(&entry{key, val})",
        "	c.m[key] = elem",
        "}",
        "",
        "func main() {",
        "	var cap, n int",
        "	if _, err := fmt.Scan(&cap, &n); err != nil {",
        "		return",
        "	}",
        "	cache := NewLRUCache(cap)",
        "	for i := 0; i < n; i++ {",
        "		var op string",
        "		var val int",
        "		fmt.Scan(&op, &val)",
        '		if op == "VIEW" {',
        "			cache.Put(val, val)",
        '		} else if op == "GET" {',
        "			fmt.Println(cache.Get(val))",
        "		}",
        "	}",
        "}",
      ].join("\n"),
    },
    publicTestCases: [
      {
        description: "Capacity 2 operations",
        input: "2 5\nVIEW 101\nVIEW 102\nGET 101\nVIEW 103\nGET 102",
        expectedOutput: "101\n-1",
      },
    ],
    hiddenTestCases: [
      {
        input: "1 3\nVIEW 50\nGET 50\nVIEW 60\nGET 50",
        expectedOutput: "50\n-1",
      },
    ],
    postSolutionExplanation: {
      dsaUsed: "LRU Cache (HashMap + Doubly Linked List)",
      why: "A HashMap provides O(1) key lookups, while a Doubly Linked List maintains insertion and access order. Together, they allow O(1) retrieval and O(1) eviction of the least recently used item.",
      timeComplexity: "O(1) average time for both GET and PUT operations.",
      spaceComplexity: "O(C) memory overhead strictly proportional to cache capacity C.",
      realWorldApplications: [
        "Web browser page cache & back button history",
        "Database buffer pools (PostgreSQL, MySQL InnoDB buffer pool)",
        "CDN content caching (Cloudflare, Akamai edge servers)",
        "Mobile App recently viewed items & image thumbnail cache",
      ],
    },
  },
];
